/**
 * Brand Puzzles - 175 puzzles
 */
const BRAND_PUZZLES = {
    easy: [
        { id: 'b1', emojis: ['🍎', '📱'], answer: 'Apple', hints: ['Tech', 'iPhone', 'Mac'] },
        { id: 'b2', emojis: ['🎯', '🛒'], answer: 'Target', hints: ['Retail', 'Red', 'Store'] },
        { id: 'b3', emojis: ['☕', '🧜‍♀️'], answer: 'Starbucks', hints: ['Coffee', 'Green', 'Seattle'] },
        { id: 'b4', emojis: ['👟', '✔️'], answer: 'Nike', hints: ['Sports', 'Swoosh', 'Just Do It'] },
        { id: 'b5', emojis: ['🍔', '🤡'], answer: 'McDonalds', hints: ['Fast Food', 'Golden Arches', 'Burger'] },
        { id: 'b6', emojis: ['📦', '😊'], answer: 'Amazon', hints: ['Shopping', 'Prime', 'Bezos'] },
        { id: 'b7', emojis: ['🎬', '📺'], answer: 'Netflix', hints: ['Streaming', 'Movies', 'Series'] },
        { id: 'b8', emojis: ['🐦', '💬'], answer: 'Twitter', hints: ['Social', 'Tweets', 'Blue'] },
        { id: 'b9', emojis: ['📸', '📱'], answer: 'Instagram', hints: ['Photos', 'Social', 'Meta'] },
        { id: 'b10', emojis: ['🔵', '👥'], answer: 'Facebook', hints: ['Social', 'Meta', 'Zuckerberg'] },
        { id: 'b11', emojis: ['🚗', '⚡'], answer: 'Tesla', hints: ['Electric', 'Musk', 'Cars'] },
        { id: 'b12', emojis: ['🎮', '🟢'], answer: 'Xbox', hints: ['Microsoft', 'Gaming', 'Console'] },
        { id: 'b13', emojis: ['🔎', '🌐'], answer: 'Google', hints: ['Search', 'Tech', 'Alphabet'] },
        { id: 'b14', emojis: ['📺', '▶️'], answer: 'YouTube', hints: ['Video', 'Google', 'Streaming'] },
        { id: 'b15', emojis: ['🎵', '🟢'], answer: 'Spotify', hints: ['Music', 'Streaming', 'Podcast'] },
        { id: 'b16', emojis: ['🛋️', '🔧'], answer: 'IKEA', hints: ['Furniture', 'Swedish', 'Assembly'] },
        { id: 'b17', emojis: ['🍕', '🛵'], answer: 'Dominos', hints: ['Pizza', 'Delivery', 'Fast Food'] },
        { id: 'b18', emojis: ['💳', '🔵'], answer: 'Visa', hints: ['Payment', 'Card', 'Banking'] },
        { id: 'b19', emojis: ['🎧', '🅱️'], answer: 'Beats', hints: ['Audio', 'Apple', 'Headphones'] },
        { id: 'b20', emojis: ['🏠', '🛏️'], answer: 'Airbnb', hints: ['Travel', 'Rental', 'Vacation'] },
        { id: 'b21', emojis: ['🍦', '🐄'], answer: 'Ben and Jerrys', hints: ['Ice Cream', 'Vermont', 'Flavors'] },
        { id: 'b22', emojis: ['🎢', '🏰'], answer: 'Disney', hints: ['Theme Park', 'Magic', 'Mickey'] },
        { id: 'b23', emojis: ['🥤', '🔴'], answer: 'Coca-Cola', hints: ['Soda', 'Red', 'Atlanta'] },
        { id: 'b24', emojis: ['🍟', '👑'], answer: 'Burger King', hints: ['Fast Food', 'Flame', 'Whopper'] },
        { id: 'b25', emojis: ['🌮', '🔔'], answer: 'Taco Bell', hints: ['Mexican', 'Fast Food', 'Chalupa'] },
        { id: 'b26', emojis: ['🐔', '🪣'], answer: 'KFC', hints: ['Fried Chicken', 'Colonel', 'Finger Lickin'] },
        { id: 'b27', emojis: ['🏃', '3️⃣'], answer: 'Adidas', hints: ['Sports', 'Stripes', 'German'] },
        { id: 'b28', emojis: ['📱', '🇰🇷'], answer: 'Samsung', hints: ['Electronics', 'Korean', 'Galaxy'] },
        { id: 'b29', emojis: ['🎮', '🔵'], answer: 'PlayStation', hints: ['Sony', 'Gaming', 'Console'] },
        { id: 'b30', emojis: ['🍩', '☕'], answer: 'Dunkin', hints: ['Coffee', 'Donuts', 'America Runs'] },
        { id: 'b31', emojis: ['🚙', '🔵', '⚪'], answer: 'BMW', hints: ['German', 'Luxury', 'Cars'] },
        { id: 'b32', emojis: ['✈️', '🔵'], answer: 'JetBlue', hints: ['Airline', 'Budget', 'Travel'] },
        { id: 'b33', emojis: ['📱', '🍎'], answer: 'iPhone', hints: ['Apple', 'Smartphone', 'iOS'] },
        { id: 'b34', emojis: ['🏀', '🧡'], answer: 'NBA', hints: ['Basketball', 'Sports', 'League'] },
        { id: 'b35', emojis: ['⚾', '🔴'], answer: 'MLB', hints: ['Baseball', 'Sports', 'League'] },
        { id: 'b36', emojis: ['🏈', '🟤'], answer: 'NFL', hints: ['Football', 'Sports', 'League'] },
        { id: 'b37', emojis: ['🧴', '👶'], answer: 'Johnson and Johnson', hints: ['Baby', 'Health', 'Products'] },
        { id: 'b38', emojis: ['🪥', '😁'], answer: 'Colgate', hints: ['Toothpaste', 'Dental', 'Smile'] },
        { id: 'b39', emojis: ['🧼', '🫧'], answer: 'Dove', hints: ['Soap', 'Beauty', 'Unilever'] },
        { id: 'b40', emojis: ['👗', '🛍️'], answer: 'Zara', hints: ['Fashion', 'Spanish', 'Fast Fashion'] },
        { id: 'b41', emojis: ['👟', '⭐'], answer: 'Converse', hints: ['Shoes', 'Chuck Taylor', 'Classic'] },
        { id: 'b42', emojis: ['🍫', '🥛'], answer: 'Hersheys', hints: ['Chocolate', 'Pennsylvania', 'Candy'] },
        { id: 'b43', emojis: ['🍬', '🌈'], answer: 'Skittles', hints: ['Candy', 'Rainbow', 'Taste'] },
        { id: 'b44', emojis: ['🍪', '🥛'], answer: 'Oreo', hints: ['Cookie', 'Twist', 'Nabisco'] },
        { id: 'b45', emojis: ['🥣', '🐯'], answer: 'Frosted Flakes', hints: ['Cereal', 'Tony', 'Kelloggs'] },
        { id: 'b46', emojis: ['🐰', '🥣'], answer: 'Trix', hints: ['Cereal', 'Rabbit', 'For Kids'] },
        { id: 'b47', emojis: ['🧲', '🅿️'], answer: 'PayPal', hints: ['Payment', 'Online', 'eBay'] },
        { id: 'b48', emojis: ['📦', '🏠'], answer: 'UPS', hints: ['Shipping', 'Brown', 'Delivery'] },
        { id: 'b49', emojis: ['📦', '💜'], answer: 'FedEx', hints: ['Shipping', 'Express', 'Delivery'] },
        { id: 'b50', emojis: ['🎁', '📱'], answer: 'Wish', hints: ['Shopping', 'Cheap', 'App'] },
        { id: 'b51', emojis: ['🛒', '💚'], answer: 'Whole Foods', hints: ['Grocery', 'Organic', 'Amazon'] },
        { id: 'b52', emojis: ['🍌', '🏷️'], answer: 'Chiquita', hints: ['Banana', 'Fruit', 'Yellow'] },
        { id: 'b53', emojis: ['🥜', '🟤'], answer: 'Planters', hints: ['Peanuts', 'Mr Peanut', 'Snacks'] },
        { id: 'b54', emojis: ['🧴', '💆'], answer: 'Pantene', hints: ['Shampoo', 'Hair', 'PG'] },
        { id: 'b55', emojis: ['🍺', '👑'], answer: 'Budweiser', hints: ['Beer', 'King', 'America'] },
        { id: 'b56', emojis: ['🎥', '🦁'], answer: 'MGM', hints: ['Movies', 'Leo', 'Hollywood'] },
        { id: 'b57', emojis: ['🏨', '💚'], answer: 'Holiday Inn', hints: ['Hotel', 'Travel', 'IHG'] },
        { id: 'b58', emojis: ['🛫', '🔺'], answer: 'Delta', hints: ['Airline', 'Atlanta', 'Travel'] },
    ],
    medium: [
        { id: 'b59', emojis: ['💎', '⌚'], answer: 'Rolex', hints: ['Watch', 'Luxury', 'Swiss'] },
        { id: 'b60', emojis: ['🐊', '👕'], answer: 'Lacoste', hints: ['Fashion', 'French', 'Tennis'] },
        { id: 'b61', emojis: ['🐴', '👔'], answer: 'Ralph Lauren', hints: ['Fashion', 'Polo', 'American'] },
        { id: 'b62', emojis: ['🦅', '🇺🇸'], answer: 'American Eagle', hints: ['Clothing', 'Retail', 'Teen'] },
        { id: 'b63', emojis: ['🐆', '🚗'], answer: 'Jaguar', hints: ['Cars', 'British', 'Luxury'] },
        { id: 'b64', emojis: ['🦁', '🎬'], answer: 'MGM', hints: ['Movies', 'Hollywood', 'Roar'] },
        { id: 'b65', emojis: ['🐚', '⛽'], answer: 'Shell', hints: ['Gas', 'Oil', 'Energy'] },
        { id: 'b66', emojis: ['🌺', '🧴'], answer: 'Hawaiian Tropic', hints: ['Sunscreen', 'Beach', 'Skincare'] },
        { id: 'b67', emojis: ['🐄', '🧀'], answer: 'Laughing Cow', hints: ['Cheese', 'French', 'Spread'] },
        { id: 'b68', emojis: ['🐻', '🍺'], answer: 'Bundaberg', hints: ['Ginger Beer', 'Australian', 'Drink'] },
        { id: 'b69', emojis: ['🦌', '🚜'], answer: 'John Deere', hints: ['Tractors', 'Farm', 'Green'] },
        { id: 'b70', emojis: ['🐎', '🚗'], answer: 'Ferrari', hints: ['Cars', 'Italian', 'Racing'] },
        { id: 'b71', emojis: ['🐂', '🥤'], answer: 'Red Bull', hints: ['Energy Drink', 'Wings', 'Sports'] },
        { id: 'b72', emojis: ['🐍', '🚗'], answer: 'Alfa Romeo', hints: ['Cars', 'Italian', 'Racing'] },
        { id: 'b73', emojis: ['🐝', '🍺'], answer: 'Bumble Bee', hints: ['Tuna', 'Canned', 'Seafood'] },
        { id: 'b74', emojis: ['🦅', '📮'], answer: 'USPS', hints: ['Mail', 'Postal', 'Government'] },
        { id: 'b75', emojis: ['🐯', '⛽'], answer: 'Exxon', hints: ['Gas', 'Oil', 'Tiger'] },
        { id: 'b76', emojis: ['🦎', '🚗'], answer: 'Gecko', hints: ['Geico', 'Insurance', 'Lizard'] },
        { id: 'b77', emojis: ['🦆', '🔧'], answer: 'Duck Brand', hints: ['Tape', 'DIY', 'Duct Tape'] },
        { id: 'b78', emojis: ['🐓', '🍜'], answer: 'Nongshim', hints: ['Ramen', 'Korean', 'Noodles'] },
        { id: 'b79', emojis: ['🐙', '🚀'], answer: 'GitHub', hints: ['Code', 'Microsoft', 'Developer'] },
        { id: 'b80', emojis: ['🐘', '🗄️'], answer: 'PostgreSQL', hints: ['Database', 'Open Source', 'Tech'] },
        { id: 'b81', emojis: ['🐋', '🐳'], answer: 'Docker', hints: ['Containers', 'DevOps', 'Tech'] },
        { id: 'b82', emojis: ['🐧', '💻'], answer: 'Linux', hints: ['Operating System', 'Open Source', 'Penguin'] },
        { id: 'b83', emojis: ['🦊', '🔥'], answer: 'Firefox', hints: ['Browser', 'Mozilla', 'Web'] },
        { id: 'b84', emojis: ['🐦', '📧'], answer: 'Thunderbird', hints: ['Email', 'Mozilla', 'Client'] },
        { id: 'b85', emojis: ['🐍', '💻'], answer: 'Python', hints: ['Programming', 'Language', 'Code'] },
        { id: 'b86', emojis: ['☕', '💻'], answer: 'Java', hints: ['Programming', 'Oracle', 'Code'] },
        { id: 'b87', emojis: ['💎', '💻'], answer: 'Ruby', hints: ['Programming', 'Language', 'Rails'] },
        { id: 'b88', emojis: ['🐙', '😸'], answer: 'GitHub', hints: ['Code', 'Version Control', 'Microsoft'] },
        { id: 'b89', emojis: ['🏔️', '⛷️'], answer: 'Patagonia', hints: ['Outdoor', 'Clothing', 'Environment'] },
        { id: 'b90', emojis: ['🧗', '🏔️'], answer: 'The North Face', hints: ['Outdoor', 'Clothing', 'Adventure'] },
        { id: 'b91', emojis: ['🐻', '🏕️'], answer: 'Grizzly', hints: ['Tobacco', 'Outdoors', 'Bear'] },
        { id: 'b92', emojis: ['🦢', '💍'], answer: 'Swarovski', hints: ['Crystal', 'Jewelry', 'Austrian'] },
        { id: 'b93', emojis: ['💎', '💍'], answer: 'Tiffany', hints: ['Jewelry', 'Blue Box', 'Luxury'] },
        { id: 'b94', emojis: ['👜', '🔶'], answer: 'Hermes', hints: ['Fashion', 'French', 'Luxury'] },
        { id: 'b95', emojis: ['👜', '🟤'], answer: 'Louis Vuitton', hints: ['Fashion', 'French', 'LV'] },
        { id: 'b96', emojis: ['👗', '🔴'], answer: 'Valentino', hints: ['Fashion', 'Italian', 'Red'] },
        { id: 'b97', emojis: ['👠', '🔴'], answer: 'Christian Louboutin', hints: ['Shoes', 'Red Sole', 'Luxury'] },
        { id: 'b98', emojis: ['🕶️', '🟡'], answer: 'Ray-Ban', hints: ['Sunglasses', 'Aviator', 'Fashion'] },
        { id: 'b99', emojis: ['⌚', '🍎'], answer: 'Apple Watch', hints: ['Smartwatch', 'Wearable', 'Tech'] },
        { id: 'b100', emojis: ['📱', '💚'], answer: 'Android', hints: ['Google', 'Mobile', 'Robot'] },
        { id: 'b101', emojis: ['🪟', '💻'], answer: 'Microsoft', hints: ['Windows', 'Tech', 'Gates'] },
        { id: 'b102', emojis: ['🎮', '🔴'], answer: 'Nintendo', hints: ['Gaming', 'Japanese', 'Mario'] },
        { id: 'b103', emojis: ['🎮', '👾'], answer: 'Atari', hints: ['Gaming', 'Retro', 'Classic'] },
        { id: 'b104', emojis: ['🎬', '📺'], answer: 'HBO', hints: ['Premium', 'TV', 'Streaming'] },
        { id: 'b105', emojis: ['🏰', '➕'], answer: 'Disney Plus', hints: ['Streaming', 'Disney', 'Marvel'] },
        { id: 'b106', emojis: ['🎬', '🍿'], answer: 'AMC', hints: ['Theater', 'Movies', 'Cinema'] },
        { id: 'b107', emojis: ['📻', '🎵'], answer: 'Pandora', hints: ['Music', 'Streaming', 'Radio'] },
        { id: 'b108', emojis: ['🎧', '🍎'], answer: 'Apple Music', hints: ['Streaming', 'Music', 'iTunes'] },
        { id: 'b109', emojis: ['📚', '🔥'], answer: 'Kindle', hints: ['Amazon', 'E-Reader', 'Books'] },
        { id: 'b110', emojis: ['🎤', '🎵'], answer: 'SoundCloud', hints: ['Music', 'Streaming', 'Upload'] },
        { id: 'b111', emojis: ['📸', '👻'], answer: 'Snapchat', hints: ['Social', 'Photos', 'Disappearing'] },
        { id: 'b112', emojis: ['🎵', '🎬'], answer: 'TikTok', hints: ['Social', 'Video', 'Short Form'] },
        { id: 'b113', emojis: ['📌', '📸'], answer: 'Pinterest', hints: ['Social', 'Ideas', 'Boards'] },
        { id: 'b114', emojis: ['💼', '🔵'], answer: 'LinkedIn', hints: ['Professional', 'Networking', 'Jobs'] },
        { id: 'b115', emojis: ['🎮', '💜'], answer: 'Twitch', hints: ['Streaming', 'Gaming', 'Live'] },
        { id: 'b116', emojis: ['📱', '🚗'], answer: 'Uber', hints: ['Rideshare', 'Transport', 'App'] },
        { id: 'b117', emojis: ['📱', '💗'], answer: 'Lyft', hints: ['Rideshare', 'Pink', 'Transport'] },
    ],
    hard: [
        { id: 'b118', emojis: ['🌙', '⭐', '☕'], answer: 'Starbucks', hints: ['Coffee', 'Siren', 'Seattle'] },
        { id: 'b119', emojis: ['🏹', '📦'], answer: 'Amazon', hints: ['Arrow', 'A to Z', 'Smile'] },
        { id: 'b120', emojis: ['🔔', '📞'], answer: 'Taco Bell', hints: ['Mexican', 'Fast Food', 'Live Mas'] },
        { id: 'b121', emojis: ['👴', '🍗'], answer: 'KFC', hints: ['Colonel Sanders', 'Chicken', 'Kentucky'] },
        { id: 'b122', emojis: ['🏠', '📦'], answer: 'Home Depot', hints: ['Hardware', 'DIY', 'Orange'] },
        { id: 'b123', emojis: ['🔵', '🏠'], answer: 'Lowes', hints: ['Hardware', 'Home', 'Blue'] },
        { id: 'b124', emojis: ['⭕', '🎯'], answer: 'Target', hints: ['Retail', 'Bullseye', 'Red'] },
        { id: 'b125', emojis: ['⭐', '💵'], answer: 'Star Market', hints: ['Grocery', 'Boston', 'Food'] },
        { id: 'b126', emojis: ['🏔️', '💧'], answer: 'Evian', hints: ['Water', 'French', 'Alps'] },
        { id: 'b127', emojis: ['🌊', '💧'], answer: 'Aquafina', hints: ['Water', 'Pepsi', 'Bottled'] },
        { id: 'b128', emojis: ['🏔️', '🧊'], answer: 'Coors', hints: ['Beer', 'Colorado', 'Rockies'] },
        { id: 'b129', emojis: ['🍀', '🥛'], answer: 'Lucky Charms', hints: ['Cereal', 'Marshmallows', 'General Mills'] },
        { id: 'b130', emojis: ['🐰', '🔋'], answer: 'Energizer', hints: ['Battery', 'Bunny', 'Power'] },
        { id: 'b131', emojis: ['🐕', '🍖'], answer: 'Purina', hints: ['Pet Food', 'Dog', 'Nestle'] },
        { id: 'b132', emojis: ['🐱', '🥫'], answer: 'Fancy Feast', hints: ['Cat Food', 'Gourmet', 'Purina'] },
        { id: 'b133', emojis: ['🦷', '✨'], answer: 'Crest', hints: ['Toothpaste', 'PG', 'Dental'] },
        { id: 'b134', emojis: ['🧻', '🐻'], answer: 'Charmin', hints: ['Toilet Paper', 'Bears', 'Soft'] },
        { id: 'b135', emojis: ['💪', '🧼'], answer: 'Mr Clean', hints: ['Cleaning', 'Bald', 'PG'] },
        { id: 'b136', emojis: ['🌸', '🧴'], answer: 'Olay', hints: ['Skincare', 'Beauty', 'PG'] },
        { id: 'b137', emojis: ['💎', '🧴'], answer: 'Head and Shoulders', hints: ['Shampoo', 'Dandruff', 'PG'] },
        { id: 'b138', emojis: ['🌊', '🧴'], answer: 'Tide', hints: ['Laundry', 'Detergent', 'PG'] },
        { id: 'b139', emojis: ['🐝', '🧴'], answer: 'Burts Bees', hints: ['Lip Balm', 'Natural', 'Skincare'] },
        { id: 'b140', emojis: ['🌿', '🧴'], answer: 'Herbal Essences', hints: ['Shampoo', 'Hair', 'Clairol'] },
        { id: 'b141', emojis: ['🐄', '🍦'], answer: 'Blue Bunny', hints: ['Ice Cream', 'Wells', 'Frozen'] },
        { id: 'b142', emojis: ['🍨', '🏠'], answer: 'Haagen-Dazs', hints: ['Ice Cream', 'Premium', 'Nestle'] },
        { id: 'b143', emojis: ['🍦', '🤴'], answer: 'Dairy Queen', hints: ['Ice Cream', 'Fast Food', 'Blizzard'] },
        { id: 'b144', emojis: ['🍕', '🛖'], answer: 'Pizza Hut', hints: ['Pizza', 'Fast Food', 'Yum'] },
        { id: 'b145', emojis: ['🍕', '👨'], answer: 'Papa Johns', hints: ['Pizza', 'Delivery', 'Better'] },
        { id: 'b146', emojis: ['🥪', '🚇'], answer: 'Subway', hints: ['Sandwiches', 'Fast Food', 'Fresh'] },
        { id: 'b147', emojis: ['🥪', '🛒'], answer: 'Jimmy Johns', hints: ['Sandwiches', 'Freaky Fast', 'Delivery'] },
        { id: 'b148', emojis: ['🌯', '🇲🇽'], answer: 'Chipotle', hints: ['Mexican', 'Burrito', 'Fast Casual'] },
        { id: 'b149', emojis: ['🍗', '🐔'], answer: 'Popeyes', hints: ['Chicken', 'Louisiana', 'Fast Food'] },
        { id: 'b150', emojis: ['🥤', '🧊'], answer: 'Slurpee', hints: ['7-Eleven', 'Frozen', 'Drink'] },
        { id: 'b151', emojis: ['☕', '🍀'], answer: 'Dunkin', hints: ['Coffee', 'Donuts', 'Boston'] },
        { id: 'b152', emojis: ['🍩', '🔴'], answer: 'Krispy Kreme', hints: ['Donuts', 'Hot Now', 'Glazed'] },
        { id: 'b153', emojis: ['🥣', '🐝'], answer: 'Cheerios', hints: ['Cereal', 'Oats', 'General Mills'] },
        { id: 'b154', emojis: ['🥣', '🍫'], answer: 'Cocoa Puffs', hints: ['Cereal', 'Cuckoo', 'General Mills'] },
        { id: 'b155', emojis: ['🥣', '🍯'], answer: 'Honey Nut Cheerios', hints: ['Cereal', 'Bee', 'General Mills'] },
        { id: 'b156', emojis: ['🍫', '🥛'], answer: 'Nesquik', hints: ['Chocolate Milk', 'Bunny', 'Nestle'] },
        { id: 'b157', emojis: ['🍫', '🥜'], answer: 'Snickers', hints: ['Candy Bar', 'Mars', 'Peanuts'] },
        { id: 'b158', emojis: ['🍫', '🥥'], answer: 'Mounds', hints: ['Candy', 'Coconut', 'Hershey'] },
        { id: 'b159', emojis: ['🍫', '🧇'], answer: 'KitKat', hints: ['Candy', 'Break', 'Nestle'] },
        { id: 'b160', emojis: ['🍬', '🫧'], answer: 'Mentos', hints: ['Mint', 'Fresh', 'Candy'] },
        { id: 'b161', emojis: ['🍬', '❄️'], answer: 'Ice Breakers', hints: ['Gum', 'Mint', 'Hershey'] },
        { id: 'b162', emojis: ['🍬', '🌈'], answer: 'Starburst', hints: ['Candy', 'Fruit', 'Mars'] },
        { id: 'b163', emojis: ['🍬', '🐻'], answer: 'Haribo', hints: ['Gummy Bears', 'German', 'Candy'] },
        { id: 'b164', emojis: ['🥤', '🍋'], answer: 'Sprite', hints: ['Soda', 'Lemon Lime', 'Coca-Cola'] },
        { id: 'b165', emojis: ['🥤', '🍊'], answer: 'Fanta', hints: ['Soda', 'Orange', 'Coca-Cola'] },
        { id: 'b166', emojis: ['🥤', '🏔️'], answer: 'Mountain Dew', hints: ['Soda', 'Green', 'PepsiCo'] },
        { id: 'b167', emojis: ['🥤', '🌶️'], answer: 'Dr Pepper', hints: ['Soda', '23 Flavors', 'Unique'] },
        { id: 'b168', emojis: ['🥤', '🟣'], answer: 'Welchs', hints: ['Grape', 'Juice', 'Fruit'] },
        { id: 'b169', emojis: ['🧃', '🍎'], answer: 'Apple and Eve', hints: ['Juice', 'Organic', 'Kids'] },
        { id: 'b170', emojis: ['🍷', '🍇'], answer: 'Gallo', hints: ['Wine', 'California', 'Vineyard'] },
        { id: 'b171', emojis: ['🍺', '🦅'], answer: 'Anheuser-Busch', hints: ['Beer', 'Budweiser', 'Eagle'] },
        { id: 'b172', emojis: ['🍺', '🌙'], answer: 'Blue Moon', hints: ['Beer', 'Belgian', 'Craft'] },
        { id: 'b173', emojis: ['🍺', '🦁'], answer: 'Lowenbrau', hints: ['Beer', 'German', 'Munich'] },
        { id: 'b174', emojis: ['🍺', '⭐'], answer: 'Heineken', hints: ['Beer', 'Dutch', 'Green'] },
        { id: 'b175', emojis: ['🍺', '🌊'], answer: 'Corona', hints: ['Beer', 'Mexican', 'Lime'] },
    ],
};

window.BRAND_PUZZLES = BRAND_PUZZLES;
