/**
 * Movie Puzzles - 250 puzzles
 */
const MOVIE_PUZZLES = {
    easy: [
        { id: 'm1', emojis: ['🦁', '👑'], answer: 'The Lion King', hints: ['Disney', 'Africa', 'Simba'] },
        { id: 'm2', emojis: ['🕷️', '🧑'], answer: 'Spider-Man', hints: ['Marvel', 'Hero', 'Web'] },
        { id: 'm3', emojis: ['⭐', '⚔️'], answer: 'Star Wars', hints: ['Space', 'Jedi', 'Force'] },
        { id: 'm4', emojis: ['🧊', '❄️', '👸'], answer: 'Frozen', hints: ['Disney', 'Sister', 'Elsa'] },
        { id: 'm5', emojis: ['🦇', '🧑'], answer: 'Batman', hints: ['DC', 'Gotham', 'Dark'] },
        { id: 'm6', emojis: ['👻', '🚫'], answer: 'Ghostbusters', hints: ['Comedy', '80s', 'Slimer'] },
        { id: 'm7', emojis: ['🧙', '💍'], answer: 'Lord of the Rings', hints: ['Fantasy', 'Hobbit', 'Frodo'] },
        { id: 'm8', emojis: ['🦖', '🏞️'], answer: 'Jurassic Park', hints: ['Dinosaurs', 'Island', 'Spielberg'] },
        { id: 'm9', emojis: ['🚢', '❄️', '💑'], answer: 'Titanic', hints: ['Ship', 'Romance', 'Jack'] },
        { id: 'm10', emojis: ['🤠', '🚀', '🧸'], answer: 'Toy Story', hints: ['Pixar', 'Woody', 'Buzz'] },
        { id: 'm11', emojis: ['🐠', '🔍'], answer: 'Finding Nemo', hints: ['Pixar', 'Ocean', 'Fish'] },
        { id: 'm12', emojis: ['👸', '🐸'], answer: 'The Princess and the Frog', hints: ['Disney', 'New Orleans', 'Tiana'] },
        { id: 'm13', emojis: ['🦈', '🏊'], answer: 'Jaws', hints: ['Thriller', 'Beach', 'Summer'] },
        { id: 'm14', emojis: ['🏠', '👽'], answer: 'E.T.', hints: ['Spielberg', 'Alien', 'Bike'] },
        { id: 'm15', emojis: ['🎃', '🔪'], answer: 'Halloween', hints: ['Horror', 'Michael', 'Slasher'] },
        { id: 'm16', emojis: ['🚗', '⚡'], answer: 'Cars', hints: ['Pixar', 'Racing', 'McQueen'] },
        { id: 'm17', emojis: ['👨‍🍳', '🐀'], answer: 'Ratatouille', hints: ['Pixar', 'Paris', 'Cooking'] },
        { id: 'm18', emojis: ['🧞', '🏜️'], answer: 'Aladdin', hints: ['Disney', 'Lamp', 'Genie'] },
        { id: 'm19', emojis: ['🦸', '👨‍👩‍👧‍👦'], answer: 'The Incredibles', hints: ['Pixar', 'Super', 'Family'] },
        { id: 'm20', emojis: ['💄', '👹'], answer: 'Beauty and the Beast', hints: ['Disney', 'Belle', 'Rose'] },
        { id: 'm21', emojis: ['🌊', '🧜‍♀️'], answer: 'The Little Mermaid', hints: ['Disney', 'Ariel', 'Ocean'] },
        { id: 'm22', emojis: ['🎪', '🐘'], answer: 'Dumbo', hints: ['Disney', 'Circus', 'Flying'] },
        { id: 'm23', emojis: ['⬆️', '🏠'], answer: 'Up', hints: ['Pixar', 'Balloons', 'Adventure'] },
        { id: 'm24', emojis: ['🤖', '❤️'], answer: 'WALL-E', hints: ['Pixar', 'Robot', 'Space'] },
        { id: 'm25', emojis: ['🏹', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'], answer: 'Brave', hints: ['Pixar', 'Scotland', 'Princess'] },
        { id: 'm26', emojis: ['🐒', '👑'], answer: 'King Kong', hints: ['Monster', 'Empire State', 'Ape'] },
        { id: 'm27', emojis: ['🎅', '🎄'], answer: 'The Santa Clause', hints: ['Christmas', 'Tim Allen', 'Holiday'] },
        { id: 'm28', emojis: ['🧒', '🏠', '🎄'], answer: 'Home Alone', hints: ['Christmas', 'Kevin', 'Burglars'] },
        { id: 'm29', emojis: ['🦈', '🌪️'], answer: 'Sharknado', hints: ['Syfy', 'Disaster', 'Sharks'] },
        { id: 'm30', emojis: ['👨', '🐕'], answer: 'John Wick', hints: ['Keanu', 'Assassin', 'Action'] },
        { id: 'm31', emojis: ['🚂', '❄️'], answer: 'Polar Express', hints: ['Christmas', 'Train', 'Animation'] },
        { id: 'm32', emojis: ['🐶', '📺'], answer: '101 Dalmatians', hints: ['Disney', 'Dogs', 'Cruella'] },
        { id: 'm33', emojis: ['🧚', '✨'], answer: 'Tinker Bell', hints: ['Disney', 'Fairy', 'Pixie'] },
        { id: 'm34', emojis: ['🤴', '🇪🇬'], answer: 'The Prince of Egypt', hints: ['Moses', 'Animation', 'DreamWorks'] },
        { id: 'm35', emojis: ['🐝', '🎬'], answer: 'Bee Movie', hints: ['Jerry Seinfeld', 'Animation', 'Honey'] },
        { id: 'm36', emojis: ['🦊', '🐰'], answer: 'Zootopia', hints: ['Disney', 'Animals', 'City'] },
        { id: 'm37', emojis: ['👻', '🏠'], answer: 'Casper', hints: ['Friendly', 'Ghost', '90s'] },
        { id: 'm38', emojis: ['🐷', '🐑', '🎬'], answer: 'Babe', hints: ['Pig', 'Farm', 'Sheep'] },
        { id: 'm39', emojis: ['🧓', '⬆️', '🎈'], answer: 'Up', hints: ['Pixar', 'Adventure', 'Carl'] },
        { id: 'm40', emojis: ['🏎️', '💨'], answer: 'Speed Racer', hints: ['Racing', 'Wachowski', 'Anime'] },
        { id: 'm41', emojis: ['👑', '💬'], answer: 'The Kings Speech', hints: ['British', 'Royal', 'Stutter'] },
        { id: 'm42', emojis: ['🐉', '👦'], answer: 'Pete\'s Dragon', hints: ['Disney', 'Elliott', 'Fantasy'] },
        { id: 'm43', emojis: ['🎸', '🎤', '🌟'], answer: 'A Star is Born', hints: ['Music', 'Lady Gaga', 'Romance'] },
        { id: 'm44', emojis: ['🐕', '🛷', '❄️'], answer: 'Balto', hints: ['Sled', 'Alaska', 'Animation'] },
        { id: 'm45', emojis: ['🌍', '🦍'], answer: 'Planet of the Apes', hints: ['Sci-Fi', 'Apes', 'Future'] },
        { id: 'm46', emojis: ['🎩', '🐰'], answer: 'Alice in Wonderland', hints: ['Disney', 'Rabbit', 'Tea Party'] },
        { id: 'm47', emojis: ['🚀', '🌙'], answer: 'Apollo 13', hints: ['Space', 'NASA', 'Tom Hanks'] },
        { id: 'm48', emojis: ['🧟', '🌎'], answer: 'World War Z', hints: ['Zombies', 'Brad Pitt', 'Apocalypse'] },
        { id: 'm49', emojis: ['🦎', '🧪'], answer: 'The Amazing Spider-Man', hints: ['Lizard', 'Marvel', 'Andrew Garfield'] },
        { id: 'm50', emojis: ['🐼', '🥋'], answer: 'Kung Fu Panda', hints: ['DreamWorks', 'Po', 'Martial Arts'] },
        { id: 'm51', emojis: ['👨‍🚀', '🔴'], answer: 'The Martian', hints: ['Mars', 'Matt Damon', 'NASA'] },
        { id: 'm52', emojis: ['🤡', '🎈'], answer: 'It', hints: ['Horror', 'Pennywise', 'Stephen King'] },
        { id: 'm53', emojis: ['🧙‍♂️', '📚'], answer: 'Harry Potter', hints: ['Hogwarts', 'Magic', 'Wizard'] },
        { id: 'm54', emojis: ['🦴', '🐕', '🏠'], answer: 'Marley and Me', hints: ['Dog', 'Family', 'Drama'] },
        { id: 'm55', emojis: ['🏰', '👸', '🐉'], answer: 'Shrek', hints: ['DreamWorks', 'Ogre', 'Fairy Tale'] },
        { id: 'm56', emojis: ['🎭', '🎶'], answer: 'The Phantom of the Opera', hints: ['Musical', 'Mask', 'Broadway'] },
        { id: 'm57', emojis: ['🚁', '🔥', '🌲'], answer: 'Only the Brave', hints: ['Firefighters', 'True Story', 'Arizona'] },
        { id: 'm58', emojis: ['👨', '🔨', '⚡'], answer: 'Thor', hints: ['Marvel', 'Asgard', 'Hammer'] },
        { id: 'm59', emojis: ['🐜', '🦸'], answer: 'Ant-Man', hints: ['Marvel', 'Shrink', 'Heist'] },
        { id: 'm60', emojis: ['🦅', '👁️'], answer: 'Bird Box', hints: ['Netflix', 'Blindfold', 'Sandra Bullock'] },
        { id: 'm61', emojis: ['🏊‍♂️', '🔍', '🐠'], answer: 'Finding Dory', hints: ['Pixar', 'Sequel', 'Memory'] },
        { id: 'm62', emojis: ['🎻', '🚢'], answer: 'Titanic', hints: ['Rose', 'Jack', 'Iceberg'] },
        { id: 'm63', emojis: ['🧛', '💕'], answer: 'Twilight', hints: ['Vampires', 'Romance', 'Teen'] },
        { id: 'm64', emojis: ['🏹', '🎯', '🔥'], answer: 'The Hunger Games', hints: ['Katniss', 'District', 'Arena'] },
        { id: 'm65', emojis: ['🐢', '🥷'], answer: 'Teenage Mutant Ninja Turtles', hints: ['Pizza', 'Sewer', 'Splinter'] },
        { id: 'm66', emojis: ['⚡', '🚗'], answer: 'Back to the Future', hints: ['DeLorean', 'Time', 'Doc'] },
        { id: 'm67', emojis: ['👻', '💀', '🎃'], answer: 'The Nightmare Before Christmas', hints: ['Jack', 'Halloween', 'Tim Burton'] },
        { id: 'm68', emojis: ['🌹', '📖'], answer: 'Beauty and the Beast', hints: ['Belle', 'Enchanted', 'Disney'] },
        { id: 'm69', emojis: ['🐁', '👨‍🍳', '🇫🇷'], answer: 'Ratatouille', hints: ['Remy', 'Paris', 'Cooking'] },
        { id: 'm70', emojis: ['🧲', '🦸'], answer: 'Magneto', hints: ['X-Men', 'Villain', 'Metal'] },
        { id: 'm71', emojis: ['🌊', '🏄', '💀'], answer: 'Point Break', hints: ['Surfing', 'Heist', 'Keanu'] },
        { id: 'm72', emojis: ['🏎️', '👶'], answer: 'Baby Driver', hints: ['Music', 'Getaway', 'Edgar Wright'] },
        { id: 'm73', emojis: ['🦁', '🐗', '🐿️'], answer: 'The Lion King', hints: ['Timon', 'Pumbaa', 'Hakuna Matata'] },
        { id: 'm74', emojis: ['🕸️', '🏠', '👦'], answer: 'Spider-Man Homecoming', hints: ['MCU', 'Tom Holland', 'High School'] },
        { id: 'm75', emojis: ['💎', '🐕'], answer: 'Bolt', hints: ['Disney', 'Dog', 'Superpower'] },
        { id: 'm76', emojis: ['🧲', '❌', '🧬'], answer: 'X-Men', hints: ['Mutants', 'Marvel', 'Xavier'] },
        { id: 'm77', emojis: ['🔵', '👽', '🌍'], answer: 'Avatar', hints: ['Pandora', 'James Cameron', 'Blue'] },
        { id: 'm78', emojis: ['🎄', '💚', '😠'], answer: 'The Grinch', hints: ['Christmas', 'Whoville', 'Dr Seuss'] },
        { id: 'm79', emojis: ['🦇', '🃏'], answer: 'The Dark Knight', hints: ['Joker', 'Gotham', 'Heath Ledger'] },
        { id: 'm80', emojis: ['🐕', '🦌', '🏹'], answer: 'The Fox and the Hound', hints: ['Disney', 'Friendship', 'Tod'] },
        { id: 'm81', emojis: ['🌺', '🏝️', '👧'], answer: 'Moana', hints: ['Disney', 'Ocean', 'Maui'] },
        { id: 'm82', emojis: ['❄️', '⛄', '🥕'], answer: 'Frozen', hints: ['Olaf', 'Elsa', 'Anna'] },
        { id: 'm83', emojis: ['🤖', '🌍', '🔥'], answer: 'Transformers', hints: ['Robots', 'Michael Bay', 'Optimus'] },
    ],
    medium: [
        { id: 'm84', emojis: ['💭', '🛏️'], answer: 'Inception', hints: ['Nolan', 'Dream', 'Layers'] },
        { id: 'm85', emojis: ['🃏', '🦇'], answer: 'The Dark Knight', hints: ['Joker', 'Batman', 'Gotham'] },
        { id: 'm86', emojis: ['💊', '🔴', '🔵'], answer: 'The Matrix', hints: ['Neo', 'Pill', 'Reality'] },
        { id: 'm87', emojis: ['🥊', '🏆'], answer: 'Rocky', hints: ['Boxing', 'Philadelphia', 'Stallone'] },
        { id: 'm88', emojis: ['🎭', '🎤'], answer: 'The Greatest Showman', hints: ['Musical', 'Circus', 'Jackman'] },
        { id: 'm89', emojis: ['🕐', '🔙'], answer: 'Back to the Future', hints: ['DeLorean', 'Time', 'McFly'] },
        { id: 'm90', emojis: ['👨‍🚀', '🌑'], answer: 'Interstellar', hints: ['Nolan', 'Space', 'Black hole'] },
        { id: 'm91', emojis: ['🎹', '🌙'], answer: 'La La Land', hints: ['Musical', 'Jazz', 'Hollywood'] },
        { id: 'm92', emojis: ['🔪', '🛁'], answer: 'Psycho', hints: ['Hitchcock', 'Horror', 'Motel'] },
        { id: 'm93', emojis: ['🐺', '💰', '📈'], answer: 'The Wolf of Wall Street', hints: ['DiCaprio', 'Money', 'Stock'] },
        { id: 'm94', emojis: ['💀', '🏴‍☠️', '🌊'], answer: 'Pirates of the Caribbean', hints: ['Sparrow', 'Disney', 'Caribbean'] },
        { id: 'm95', emojis: ['⛓️', '🔨', '🕊️'], answer: 'The Shawshank Redemption', hints: ['Prison', 'Hope', 'Morgan'] },
        { id: 'm96', emojis: ['📋', '✡️', '🏭'], answer: 'Schindlers List', hints: ['WW2', 'Holocaust', 'Spielberg'] },
        { id: 'm97', emojis: ['🚁', '🌴', '💥'], answer: 'Apocalypse Now', hints: ['Vietnam', 'War', 'Coppola'] },
        { id: 'm98', emojis: ['🎩', '🍫'], answer: 'Charlie and the Chocolate Factory', hints: ['Wonka', 'Golden', 'Ticket'] },
        { id: 'm99', emojis: ['🏎️', '😤'], answer: 'Fast and Furious', hints: ['Cars', 'Family', 'Racing'] },
        { id: 'm100', emojis: ['🤵', '🔫'], answer: 'James Bond', hints: ['007', 'Spy', 'British'] },
        { id: 'm101', emojis: ['🐉', '🧙'], answer: 'How to Train Your Dragon', hints: ['Animation', 'Viking', 'Toothless'] },
        { id: 'm102', emojis: ['🇺🇸', '🦅', '🔫'], answer: 'American Sniper', hints: ['War', 'Bradley Cooper', 'Military'] },
        { id: 'm103', emojis: ['🎯', '🦌'], answer: 'The Deer Hunter', hints: ['Vietnam', 'War', 'Russian Roulette'] },
        { id: 'm104', emojis: ['🌙', '🐺'], answer: 'An American Werewolf in London', hints: ['Horror', 'Transformation', 'London'] },
        { id: 'm105', emojis: ['🎪', '🎭'], answer: 'The Greatest Showman', hints: ['Musical', 'Barnum', 'Hugh Jackman'] },
        { id: 'm106', emojis: ['💣', '🚂'], answer: 'Unstoppable', hints: ['Train', 'Denzel', 'Action'] },
        { id: 'm107', emojis: ['🌪️', '🏠', '🧙‍♀️'], answer: 'The Wizard of Oz', hints: ['Dorothy', 'Kansas', 'Emerald'] },
        { id: 'm108', emojis: ['🔴', '🎈', '🤡'], answer: 'It', hints: ['Pennywise', 'Horror', 'Derry'] },
        { id: 'm109', emojis: ['🐋', '📖'], answer: 'Moby Dick', hints: ['Whale', 'Captain', 'Ahab'] },
        { id: 'm110', emojis: ['⚓', '🏴‍☠️', '💀'], answer: 'Pirates of the Caribbean', hints: ['Jack Sparrow', 'Curse', 'Black Pearl'] },
        { id: 'm111', emojis: ['🤺', '👸', '💋'], answer: 'The Princess Bride', hints: ['Westley', 'Inconceivable', 'Romance'] },
        { id: 'm112', emojis: ['👽', '📞'], answer: 'E.T.', hints: ['Phone Home', 'Spielberg', 'Reeses'] },
        { id: 'm113', emojis: ['🏔️', '🎿', '🔫'], answer: 'On Her Majestys Secret Service', hints: ['Bond', 'Skiing', 'Alps'] },
        { id: 'm114', emojis: ['🦍', '💀', '🏝️'], answer: 'Kong Skull Island', hints: ['Monster', 'Soldiers', 'Island'] },
        { id: 'm115', emojis: ['🔬', '🧟'], answer: 'Resident Evil', hints: ['Umbrella', 'Zombies', 'Milla'] },
        { id: 'm116', emojis: ['🕷️', '🦎', '⚡'], answer: 'The Amazing Spider-Man', hints: ['Electro', 'Gwen', 'Andrew'] },
        { id: 'm117', emojis: ['🎰', '💰', '🤝'], answer: 'Oceans Eleven', hints: ['Heist', 'Vegas', 'Clooney'] },
        { id: 'm118', emojis: ['🗡️', '⚔️', '👑'], answer: 'Gladiator', hints: ['Rome', 'Russell Crowe', 'Maximus'] },
        { id: 'm119', emojis: ['🕷️', '🦟', '🧬'], answer: 'The Fly', hints: ['Horror', 'Transformation', 'Cronenberg'] },
        { id: 'm120', emojis: ['🐕', '🌌', '🚀'], answer: 'Guardians of the Galaxy', hints: ['Marvel', 'Rocket', 'Groot'] },
        { id: 'm121', emojis: ['💀', '📖', '☠️'], answer: 'The Book of Eli', hints: ['Post-apocalyptic', 'Denzel', 'Bible'] },
        { id: 'm122', emojis: ['🤖', '👦', '❤️'], answer: 'A.I. Artificial Intelligence', hints: ['Spielberg', 'Robot', 'David'] },
        { id: 'm123', emojis: ['🌊', '⛵', '🐯'], answer: 'Life of Pi', hints: ['Tiger', 'Ocean', 'Survival'] },
        { id: 'm124', emojis: ['👨‍🎤', '🎸', '👑'], answer: 'Bohemian Rhapsody', hints: ['Queen', 'Freddie', 'Biopic'] },
        { id: 'm125', emojis: ['🦷', '🧚'], answer: 'Tooth Fairy', hints: ['The Rock', 'Comedy', 'Wings'] },
        { id: 'm126', emojis: ['🔥', '💍', '🌋'], answer: 'Lord of the Rings', hints: ['Mordor', 'Sauron', 'Frodo'] },
        { id: 'm127', emojis: ['🐊', '🏠', '😱'], answer: 'Crawl', hints: ['Alligators', 'Hurricane', 'Horror'] },
        { id: 'm128', emojis: ['🧛', '🩸', '💕'], answer: 'Twilight', hints: ['Edward', 'Bella', 'Vampire'] },
        { id: 'm129', emojis: ['🚀', '👨‍👩‍👧', '🌽'], answer: 'Interstellar', hints: ['Nolan', 'Wormhole', 'Love'] },
        { id: 'm130', emojis: ['🗽', '🦍'], answer: 'King Kong', hints: ['New York', 'Empire State', 'Beauty'] },
        { id: 'm131', emojis: ['🏃', '🌲', '🏃'], answer: 'Forrest Gump', hints: ['Running', 'Tom Hanks', 'Shrimp'] },
        { id: 'm132', emojis: ['💔', '📓'], answer: 'The Notebook', hints: ['Romance', 'Ryan Gosling', 'Rain'] },
        { id: 'm133', emojis: ['🐀', '🍕', '🥷'], answer: 'Teenage Mutant Ninja Turtles', hints: ['Splinter', 'Shredder', 'Heroes'] },
        { id: 'm134', emojis: ['⛵', '🌊', '😰'], answer: 'Cast Away', hints: ['Wilson', 'Island', 'Tom Hanks'] },
        { id: 'm135', emojis: ['🎭', '😈'], answer: 'The Mask', hints: ['Jim Carrey', 'Green', 'Comedy'] },
        { id: 'm136', emojis: ['🐜', '🦗', '🎪'], answer: 'A Bugs Life', hints: ['Pixar', 'Circus', 'Flik'] },
        { id: 'm137', emojis: ['👨‍👩‍👦', '🏠', '🎄'], answer: 'National Lampoons Christmas Vacation', hints: ['Griswold', 'Clark', 'Holiday'] },
        { id: 'm138', emojis: ['🎹', '🧔', '🎵'], answer: 'The Pianist', hints: ['WW2', 'Holocaust', 'Warsaw'] },
        { id: 'm139', emojis: ['👻', '📷'], answer: 'Ghostbusters', hints: ['Proton', 'Pack', 'Stay Puft'] },
        { id: 'm140', emojis: ['🔦', '👽', '🏠'], answer: 'Signs', hints: ['Aliens', 'Shyamalan', 'Farm'] },
        { id: 'm141', emojis: ['🐕', '🌕', '🚀'], answer: 'Scooby-Doo', hints: ['Mystery', 'Shaggy', 'Cartoon'] },
        { id: 'm142', emojis: ['🏹', '🍎', '🎯'], answer: 'Robin Hood', hints: ['Disney', 'Sherwood', 'Arrow'] },
        { id: 'm143', emojis: ['🎸', '🚌', '🎤'], answer: 'School of Rock', hints: ['Jack Black', 'Music', 'Kids'] },
        { id: 'm144', emojis: ['👦', '🧙‍♂️', '⚡'], answer: 'Harry Potter', hints: ['Hogwarts', 'Voldemort', 'Magic'] },
        { id: 'm145', emojis: ['🐙', '🌊', '☠️'], answer: 'Pirates of the Caribbean Dead Mans Chest', hints: ['Davy Jones', 'Kraken', 'Heart'] },
        { id: 'm146', emojis: ['🎺', '🐘', '🎪'], answer: 'Dumbo', hints: ['Disney', 'Fly', 'Ears'] },
        { id: 'm147', emojis: ['🧊', '🦴', '🐿️'], answer: 'Ice Age', hints: ['Manny', 'Scrat', 'Acorn'] },
        { id: 'm148', emojis: ['🏀', '🐰', '👽'], answer: 'Space Jam', hints: ['Jordan', 'Looney Tunes', 'Basketball'] },
        { id: 'm149', emojis: ['💀', '💋', '☠️'], answer: 'The Kiss of Death', hints: ['Noir', 'Crime', 'Classic'] },
        { id: 'm150', emojis: ['🐒', '🏙️'], answer: 'Planet of the Apes', hints: ['Sci-Fi', 'Caesar', 'Apes'] },
        { id: 'm151', emojis: ['🌀', '⛈️', '🌊'], answer: 'The Perfect Storm', hints: ['Fishing', 'Clooney', 'Waves'] },
        { id: 'm152', emojis: ['💀', '🏝️', '💎'], answer: 'Treasure Island', hints: ['Pirates', 'Silver', 'Map'] },
        { id: 'm153', emojis: ['🐝', '🎥'], answer: 'Bee Movie', hints: ['Jerry Seinfeld', 'Animation', 'Lawsuit'] },
        { id: 'm154', emojis: ['🕺', '💃', '🎶'], answer: 'Dirty Dancing', hints: ['Swayze', 'Baby', 'Lift'] },
        { id: 'm155', emojis: ['🐭', '🎩', '🧙'], answer: 'Fantasia', hints: ['Disney', 'Sorcerer', 'Mickey'] },
        { id: 'm156', emojis: ['💨', '🏃', '👟'], answer: 'Forrest Gump', hints: ['Run', 'Box', 'Chocolates'] },
        { id: 'm157', emojis: ['🚗', '🔙', '⏰'], answer: 'Back to the Future', hints: ['DeLorean', '88 mph', 'Doc Brown'] },
        { id: 'm158', emojis: ['🦖', '🥚', '🧬'], answer: 'Jurassic World', hints: ['Chris Pratt', 'Theme Park', 'Indominus'] },
        { id: 'm159', emojis: ['🃏', '🎰', '💰'], answer: 'Casino Royale', hints: ['Bond', 'Poker', 'Montenegro'] },
        { id: 'm160', emojis: ['👸', '👡', '🕛'], answer: 'Cinderella', hints: ['Disney', 'Midnight', 'Glass Slipper'] },
        { id: 'm161', emojis: ['🐉', '❄️', '👧'], answer: 'Frozen 2', hints: ['Elsa', 'Spirits', 'Adventure'] },
        { id: 'm162', emojis: ['🏍️', '🔥', '💀'], answer: 'Ghost Rider', hints: ['Nicolas Cage', 'Marvel', 'Hell'] },
        { id: 'm163', emojis: ['🌪️', '🐮', '🚜'], answer: 'Twister', hints: ['Storm', 'Chasers', 'Helen Hunt'] },
        { id: 'm164', emojis: ['⬛', '🐆'], answer: 'Black Panther', hints: ['Wakanda', 'Marvel', 'TChalla'] },
        { id: 'm165', emojis: ['👨‍🎤', '🚀', '⭐'], answer: 'Rocketman', hints: ['Elton John', 'Biopic', 'Music'] },
        { id: 'm166', emojis: ['🕷️', '🎭', '🌆'], answer: 'Spider-Man Into the Spider-Verse', hints: ['Miles', 'Animation', 'Multiverse'] },
    ],
    hard: [
        { id: 'm167', emojis: ['🕯️', '🍽️', '💀'], answer: 'The Cook the Thief His Wife and Her Lover', hints: ['Drama', 'British', 'Greenaway'] },
        { id: 'm168', emojis: ['🌀', '👁️'], answer: 'Vertigo', hints: ['Hitchcock', 'Fear', 'Heights'] },
        { id: 'm169', emojis: ['😍', '🧠'], answer: 'A Beautiful Mind', hints: ['Math', 'Nash', 'Schizophrenia'] },
        { id: 'm170', emojis: ['⚫', '🦢'], answer: 'Black Swan', hints: ['Ballet', 'Thriller', 'Portman'] },
        { id: 'm171', emojis: ['🔪', '🏃', '🏙️'], answer: 'Blade Runner', hints: ['Sci-fi', 'Replicant', 'Ford'] },
        { id: 'm172', emojis: ['🧩', '🚪'], answer: 'Being John Malkovich', hints: ['Portal', 'Weird', 'Mind'] },
        { id: 'm173', emojis: ['📼', '⏪'], answer: 'Memento', hints: ['Nolan', 'Memory', 'Reverse'] },
        { id: 'm174', emojis: ['🎩', '✨', '👯'], answer: 'The Prestige', hints: ['Magic', 'Nolan', 'Tesla'] },
        { id: 'm175', emojis: ['🌌', '👶', '🧓'], answer: '2001 A Space Odyssey', hints: ['Kubrick', 'HAL', 'Monolith'] },
        { id: 'm176', emojis: ['🍊', '⏰', '🎩'], answer: 'A Clockwork Orange', hints: ['Kubrick', 'Violence', 'Dystopia'] },
        { id: 'm177', emojis: ['🎬', '🔇', '🎩'], answer: 'The Artist', hints: ['Silent', 'Black White', 'French'] },
        { id: 'm178', emojis: ['🥊', '🧼', '🤫'], answer: 'Fight Club', hints: ['Pitt', 'Norton', 'Underground'] },
        { id: 'm179', emojis: ['🤫', '🐑'], answer: 'The Silence of the Lambs', hints: ['Hannibal', 'FBI', 'Horror'] },
        { id: 'm180', emojis: ['⚔️', '👰', '🩸'], answer: 'Kill Bill', hints: ['Tarantino', 'Revenge', 'Uma'] },
        { id: 'm181', emojis: ['🚫', '🇺🇸', '👴'], answer: 'No Country for Old Men', hints: ['Coen', 'Texas', 'Chigurh'] },
        { id: 'm182', emojis: ['🛢️', '🩸'], answer: 'There Will Be Blood', hints: ['Oil', 'Daniel', 'Milkshake'] },
        { id: 'm183', emojis: ['🚪', '🧠', '💭'], answer: 'Eternal Sunshine of the Spotless Mind', hints: ['Memory', 'Love', 'Erase'] },
        { id: 'm184', emojis: ['🎰', '💎', '🃏'], answer: 'Casino', hints: ['Scorsese', 'Vegas', 'Mob'] },
        { id: 'm185', emojis: ['😈', '👗', '👠'], answer: 'The Devil Wears Prada', hints: ['Fashion', 'Meryl', 'Vogue'] },
        { id: 'm186', emojis: ['🚪', '6️⃣', '🔮'], answer: 'The Sixth Sense', hints: ['Shyamalan', 'Ghosts', 'Bruce Willis'] },
        { id: 'm187', emojis: ['🏥', '😵', '🔪'], answer: 'One Flew Over the Cuckoos Nest', hints: ['Mental', 'Nicholson', 'Nurse'] },
        { id: 'm188', emojis: ['🌧️', '🔪', '🎻'], answer: 'Se7en', hints: ['Brad Pitt', 'Sins', 'Thriller'] },
        { id: 'm189', emojis: ['🕸️', '💀', '🏠'], answer: 'House of Wax', hints: ['Horror', 'Museum', 'Paris Hilton'] },
        { id: 'm190', emojis: ['🎻', '😢', '📜'], answer: 'Schindlers List', hints: ['Holocaust', 'Spielberg', 'Oskar'] },
        { id: 'm191', emojis: ['🕴️', '💼', '😐'], answer: 'American Psycho', hints: ['Bale', 'Wall Street', 'Killer'] },
        { id: 'm192', emojis: ['🪞', '👧', '🔮'], answer: 'The Ring', hints: ['Horror', 'Video', 'Seven Days'] },
        { id: 'm193', emojis: ['🌲', '🔪', '😱'], answer: 'The Shining', hints: ['Kubrick', 'Hotel', 'Jack'] },
        { id: 'm194', emojis: ['🚁', '🔥', '🌿'], answer: 'Apocalypse Now', hints: ['Vietnam', 'Kurtz', 'Coppola'] },
        { id: 'm195', emojis: ['🎭', '👨', '2️⃣'], answer: 'Face Off', hints: ['Cage', 'Travolta', 'Switch'] },
        { id: 'm196', emojis: ['⚖️', '❓', '😨'], answer: 'Gone Girl', hints: ['Fincher', 'Marriage', 'Disappear'] },
        { id: 'm197', emojis: ['🗡️', '🇯🇵', '🩸'], answer: 'Kill Bill', hints: ['Bride', 'Revenge', 'Katana'] },
        { id: 'm198', emojis: ['🎪', '🃏', '🦇'], answer: 'Joker', hints: ['Phoenix', 'Origin', 'Gotham'] },
        { id: 'm199', emojis: ['🌑', '🔫', '🌌'], answer: 'Blade Runner 2049', hints: ['Sequel', 'Gosling', 'AI'] },
        { id: 'm200', emojis: ['🎨', '🔥', '👂'], answer: 'Van Gogh', hints: ['Artist', 'Painting', 'Ear'] },
        { id: 'm201', emojis: ['🧠', '🔫', '🎬'], answer: 'Inception', hints: ['Dream', 'Heist', 'Totem'] },
        { id: 'm202', emojis: ['🕳️', '🐰', '♠️'], answer: 'Alice in Wonderland', hints: ['Burton', 'Tea', 'Queen'] },
        { id: 'm203', emojis: ['🌊', '🦑', '⚓'], answer: 'Master and Commander', hints: ['Navy', 'Russell Crowe', 'Ship'] },
        { id: 'm204', emojis: ['🏜️', '🪱', '🌶️'], answer: 'Dune', hints: ['Spice', 'Sandworm', 'Arrakis'] },
        { id: 'm205', emojis: ['👩‍🎤', '🎤', '⭐'], answer: 'A Star is Born', hints: ['Gaga', 'Cooper', 'Music'] },
        { id: 'm206', emojis: ['🚪', '🎩', '🕳️'], answer: 'Get Out', hints: ['Horror', 'Peele', 'Sunken'] },
        { id: 'm207', emojis: ['🌙', '🐺', '😱'], answer: 'The Howling', hints: ['Werewolf', 'Horror', '80s'] },
        { id: 'm208', emojis: ['🍷', '🍇', '☀️'], answer: 'Sideways', hints: ['Wine', 'California', 'Comedy'] },
        { id: 'm209', emojis: ['🎭', '🌹', '👻'], answer: 'Phantom of the Opera', hints: ['Musical', 'Mask', 'Christine'] },
        { id: 'm210', emojis: ['🧊', '💀', '🏔️'], answer: 'Everest', hints: ['Climbing', 'Disaster', 'True Story'] },
        { id: 'm211', emojis: ['🗣️', '🐠', '🌊'], answer: 'Finding Nemo', hints: ['Just Keep Swimming', 'Marlin', 'Dory'] },
        { id: 'm212', emojis: ['🔵', '🐠', '🌊'], answer: 'Finding Dory', hints: ['Memory', 'Sequel', 'Pixar'] },
        { id: 'm213', emojis: ['🏃‍♂️', '🌧️', '💀'], answer: 'The Crow', hints: ['Brandon Lee', 'Revenge', 'Gothic'] },
        { id: 'm214', emojis: ['🧲', '🎱', '🔩'], answer: 'Iron Man', hints: ['Stark', 'Marvel', 'Suit'] },
        { id: 'm215', emojis: ['🎺', '🌙', '🌃'], answer: 'Whiplash', hints: ['Drums', 'Jazz', 'JK Simmons'] },
        { id: 'm216', emojis: ['🕷️', '⚫', '🕷️'], answer: 'Arachnophobia', hints: ['Spiders', 'Horror', 'Comedy'] },
        { id: 'm217', emojis: ['🎪', '👶', '🐘'], answer: 'Dumbo', hints: ['Disney', 'Flying', 'Live Action'] },
        { id: 'm218', emojis: ['⏰', '🔁', '💀'], answer: 'Edge of Tomorrow', hints: ['Tom Cruise', 'Repeat', 'Aliens'] },
        { id: 'm219', emojis: ['🤡', '💀', '🎪'], answer: 'Killer Klowns from Outer Space', hints: ['Horror', 'Comedy', 'Aliens'] },
        { id: 'm220', emojis: ['🦠', '🌍', '💀'], answer: 'Contagion', hints: ['Virus', 'Pandemic', 'Soderbergh'] },
        { id: 'm221', emojis: ['🐺', '🧛', '⚔️'], answer: 'Underworld', hints: ['Vampires', 'Werewolves', 'Kate'] },
        { id: 'm222', emojis: ['🤿', '🦈', '📷'], answer: 'The Shallows', hints: ['Surfing', 'Shark', 'Blake Lively'] },
        { id: 'm223', emojis: ['🔫', '🎰', '🤠'], answer: 'Django Unchained', hints: ['Tarantino', 'Western', 'Slavery'] },
        { id: 'm224', emojis: ['🧠', '💔', '☀️'], answer: 'Eternal Sunshine', hints: ['Memory', 'Carrey', 'Winslet'] },
        { id: 'm225', emojis: ['🗡️', '⚔️', '🏰'], answer: 'The Last Duel', hints: ['Medieval', 'Ridley Scott', 'France'] },
        { id: 'm226', emojis: ['🌙', '🧛', '💋'], answer: 'Interview with the Vampire', hints: ['Tom Cruise', 'Brad Pitt', 'Anne Rice'] },
        { id: 'm227', emojis: ['🔮', '👁️', '💀'], answer: 'Doctor Strange', hints: ['Marvel', 'Sorcerer', 'Multiverse'] },
        { id: 'm228', emojis: ['🎲', '🎰', '🔫'], answer: 'Rounders', hints: ['Poker', 'Matt Damon', 'Cards'] },
        { id: 'm229', emojis: ['🐍', '✈️', '😱'], answer: 'Snakes on a Plane', hints: ['Samuel L Jackson', 'Action', 'Comedy'] },
        { id: 'm230', emojis: ['👨‍🎨', '✂️', '🖐️'], answer: 'Edward Scissorhands', hints: ['Tim Burton', 'Johnny Depp', 'Gothic'] },
        { id: 'm231', emojis: ['🌳', '🏃', '🗡️'], answer: 'The Revenant', hints: ['DiCaprio', 'Bear', 'Survival'] },
        { id: 'm232', emojis: ['🎪', '🎭', '😢'], answer: 'The Elephant Man', hints: ['Lynch', 'Deformity', 'Victorian'] },
        { id: 'm233', emojis: ['🎬', '🔫', '💭'], answer: 'Pulp Fiction', hints: ['Tarantino', 'Briefcase', 'Dance'] },
        { id: 'm234', emojis: ['🎹', '🌧️', '💔'], answer: 'The Piano', hints: ['Campion', 'Mute', 'New Zealand'] },
        { id: 'm235', emojis: ['🦅', '🏔️', '🗡️'], answer: 'The Lord of the Rings The Return of the King', hints: ['Eagles', 'Mount Doom', 'Aragorn'] },
        { id: 'm236', emojis: ['🌊', '🔱', '👑'], answer: 'Aquaman', hints: ['DC', 'Atlantis', 'Jason Momoa'] },
        { id: 'm237', emojis: ['⚡', '🔨', '🌈'], answer: 'Thor Ragnarok', hints: ['Marvel', 'Hulk', 'Hela'] },
        { id: 'm238', emojis: ['🪨', '📿', '💎'], answer: 'Uncut Gems', hints: ['Adam Sandler', 'Gambling', 'Opal'] },
        { id: 'm239', emojis: ['🧪', '💀', '🦠'], answer: 'The Invisible Man', hints: ['Horror', 'Invisible', 'Elisabeth Moss'] },
        { id: 'm240', emojis: ['🌌', '👽', '🔫'], answer: 'Independence Day', hints: ['Aliens', 'Will Smith', 'July 4th'] },
        { id: 'm241', emojis: ['🎺', '🌃', '💋'], answer: 'Chicago', hints: ['Musical', 'Jazz', 'Murder'] },
        { id: 'm242', emojis: ['🐉', '🏯', '⚔️'], answer: 'Crouching Tiger Hidden Dragon', hints: ['Martial Arts', 'Chinese', 'Ang Lee'] },
        { id: 'm243', emojis: ['🤖', '👶', '🌍'], answer: 'Terminator 2', hints: ['Schwarzenegger', 'Skynet', 'Judgment Day'] },
        { id: 'm244', emojis: ['🌺', '🎸', '💀'], answer: 'Coco', hints: ['Pixar', 'Mexico', 'Day of Dead'] },
        { id: 'm245', emojis: ['🎭', '🏛️', '👑'], answer: 'Amadeus', hints: ['Mozart', 'Music', 'Salieri'] },
        { id: 'm246', emojis: ['📞', '😱', '🔪'], answer: 'Scream', hints: ['Horror', 'Ghostface', 'Wes Craven'] },
        { id: 'm247', emojis: ['💎', '🚂', '🔪'], answer: 'Murder on the Orient Express', hints: ['Poirot', 'Agatha Christie', 'Train'] },
        { id: 'm248', emojis: ['🧟', '😂', '🇬🇧'], answer: 'Shaun of the Dead', hints: ['Comedy', 'Zombies', 'Edgar Wright'] },
        { id: 'm249', emojis: ['🎪', '👫', '🌟'], answer: 'The Greatest Showman', hints: ['Barnum', 'Musical', 'This Is Me'] },
        { id: 'm250', emojis: ['🌙', '🎹', '🌃'], answer: 'Moonlight Sonata', hints: ['Beethoven', 'Classic', 'Piano'] },
    ],
};

window.MOVIE_PUZZLES = MOVIE_PUZZLES;
