/**
 * Place Puzzles - 175 puzzles
 */
const PLACE_PUZZLES = {
    easy: [
        { id: 'pl1', emojis: ['🗽', '🇺🇸'], answer: 'New York', hints: ['City', 'USA', 'Big Apple'] },
        { id: 'pl2', emojis: ['🗼', '🇫🇷'], answer: 'Paris', hints: ['France', 'Eiffel', 'Love'] },
        { id: 'pl3', emojis: ['🏛️', '🇮🇹'], answer: 'Rome', hints: ['Italy', 'Colosseum', 'Ancient'] },
        { id: 'pl4', emojis: ['🎰', '🌴'], answer: 'Las Vegas', hints: ['Casino', 'Nevada', 'Entertainment'] },
        { id: 'pl5', emojis: ['🐨', '🦘'], answer: 'Australia', hints: ['Continent', 'Outback', 'Sydney'] },
        { id: 'pl6', emojis: ['🗻', '🇯🇵'], answer: 'Japan', hints: ['Tokyo', 'Fuji', 'Asia'] },
        { id: 'pl7', emojis: ['🏖️', '🌺'], answer: 'Hawaii', hints: ['Islands', 'USA', 'Aloha'] },
        { id: 'pl8', emojis: ['🏰', '🐭'], answer: 'Disneyland', hints: ['Theme Park', 'Magic', 'Mickey'] },
        { id: 'pl9', emojis: ['🌉', '🌁'], answer: 'San Francisco', hints: ['California', 'Bridge', 'Bay'] },
        { id: 'pl10', emojis: ['🎭', '🎵', '🗽'], answer: 'Broadway', hints: ['Theater', 'NYC', 'Shows'] },
        { id: 'pl11', emojis: ['🌴', '🎬'], answer: 'Hollywood', hints: ['Movies', 'LA', 'Stars'] },
        { id: 'pl12', emojis: ['🏔️', '⛷️'], answer: 'Colorado', hints: ['Skiing', 'Mountains', 'Denver'] },
        { id: 'pl13', emojis: ['🎸', '🤠'], answer: 'Nashville', hints: ['Country Music', 'Tennessee', 'Grand Ole Opry'] },
        { id: 'pl14', emojis: ['🍕', '🗽'], answer: 'New York City', hints: ['Big Apple', 'Manhattan', 'USA'] },
        { id: 'pl15', emojis: ['🌊', '🏄'], answer: 'California', hints: ['Beach', 'West Coast', 'Golden State'] },
        { id: 'pl16', emojis: ['🎺', '🎭'], answer: 'New Orleans', hints: ['Jazz', 'Louisiana', 'Mardi Gras'] },
        { id: 'pl17', emojis: ['🤠', '🐂'], answer: 'Texas', hints: ['Cowboys', 'Lone Star', 'Houston'] },
        { id: 'pl18', emojis: ['🏈', '🦅'], answer: 'Philadelphia', hints: ['Eagles', 'Liberty Bell', 'Cheesesteak'] },
        { id: 'pl19', emojis: ['☕', '🌧️'], answer: 'Seattle', hints: ['Washington', 'Rain', 'Starbucks'] },
        { id: 'pl20', emojis: ['🎲', '🎰'], answer: 'Atlantic City', hints: ['Casinos', 'New Jersey', 'Boardwalk'] },
        { id: 'pl21', emojis: ['🍊', '☀️'], answer: 'Florida', hints: ['Sunshine State', 'Miami', 'Disney'] },
        { id: 'pl22', emojis: ['🌵', '☀️'], answer: 'Arizona', hints: ['Desert', 'Phoenix', 'Grand Canyon'] },
        { id: 'pl23', emojis: ['🏝️', '🌴'], answer: 'Caribbean', hints: ['Islands', 'Beach', 'Tropical'] },
        { id: 'pl24', emojis: ['🐻', '🌲'], answer: 'Yellowstone', hints: ['National Park', 'Geyser', 'Wildlife'] },
        { id: 'pl25', emojis: ['🎢', '🎡'], answer: 'Orlando', hints: ['Theme Parks', 'Florida', 'Disney World'] },
        { id: 'pl26', emojis: ['🦞', '🏖️'], answer: 'Maine', hints: ['Lobster', 'New England', 'Acadia'] },
        { id: 'pl27', emojis: ['🍁', '🏒'], answer: 'Canada', hints: ['Maple', 'Hockey', 'North'] },
        { id: 'pl28', emojis: ['🌸', '🏛️'], answer: 'Washington DC', hints: ['Capital', 'Cherry Blossoms', 'White House'] },
        { id: 'pl29', emojis: ['🎵', '🎺'], answer: 'Memphis', hints: ['Blues', 'Tennessee', 'Elvis'] },
        { id: 'pl30', emojis: ['🏀', '🌽'], answer: 'Indiana', hints: ['Basketball', 'Hoosiers', 'Indianapolis'] },
        { id: 'pl31', emojis: ['🌾', '🌻'], answer: 'Kansas', hints: ['Sunflowers', 'Midwest', 'Wizard of Oz'] },
        { id: 'pl32', emojis: ['🎭', '🌆'], answer: 'Chicago', hints: ['Windy City', 'Illinois', 'Deep Dish'] },
        { id: 'pl33', emojis: ['⛰️', '🏕️'], answer: 'Yosemite', hints: ['National Park', 'California', 'El Capitan'] },
        { id: 'pl34', emojis: ['🦅', '🗻'], answer: 'Alaska', hints: ['Last Frontier', 'Bears', 'Cold'] },
        { id: 'pl35', emojis: ['🌺', '🏝️'], answer: 'Maui', hints: ['Hawaii', 'Island', 'Beach'] },
        { id: 'pl36', emojis: ['🎰', '⛰️'], answer: 'Reno', hints: ['Nevada', 'Gambling', 'Biggest Little City'] },
        { id: 'pl37', emojis: ['🏖️', '🌴', '🇲🇽'], answer: 'Cancun', hints: ['Mexico', 'Resort', 'Caribbean'] },
        { id: 'pl38', emojis: ['🌮', '🇲🇽'], answer: 'Mexico', hints: ['Tacos', 'Spanish', 'North America'] },
        { id: 'pl39', emojis: ['☀️', '🏖️', '🇪🇸'], answer: 'Spain', hints: ['Barcelona', 'Madrid', 'Europe'] },
        { id: 'pl40', emojis: ['🍝', '🏛️'], answer: 'Italy', hints: ['Pasta', 'Rome', 'Europe'] },
        { id: 'pl41', emojis: ['🥨', '🍺', '🇩🇪'], answer: 'Germany', hints: ['Oktoberfest', 'Berlin', 'Europe'] },
        { id: 'pl42', emojis: ['🧀', '🏔️', '🇨🇭'], answer: 'Switzerland', hints: ['Alps', 'Chocolate', 'Neutral'] },
        { id: 'pl43', emojis: ['🌷', '💨'], answer: 'Netherlands', hints: ['Tulips', 'Windmills', 'Amsterdam'] },
        { id: 'pl44', emojis: ['👑', '☕'], answer: 'England', hints: ['Queen', 'Tea', 'London'] },
        { id: 'pl45', emojis: ['🏴󠁧󠁢󠁳󠁣󠁴󠁿', '🥃'], answer: 'Scotland', hints: ['Whisky', 'Highlands', 'Edinburgh'] },
        { id: 'pl46', emojis: ['☘️', '🍀'], answer: 'Ireland', hints: ['Green', 'Dublin', 'Guinness'] },
        { id: 'pl47', emojis: ['🥖', '🍷'], answer: 'France', hints: ['Wine', 'Baguette', 'Paris'] },
        { id: 'pl48', emojis: ['🐂', '💃'], answer: 'Spain', hints: ['Bullfighting', 'Flamenco', 'Madrid'] },
        { id: 'pl49', emojis: ['🍕', '🛵'], answer: 'Italy', hints: ['Vespa', 'Pizza', 'Rome'] },
        { id: 'pl50', emojis: ['⛩️', '🌸'], answer: 'Japan', hints: ['Cherry Blossoms', 'Shrine', 'Tokyo'] },
        { id: 'pl51', emojis: ['🐼', '🏯'], answer: 'China', hints: ['Panda', 'Great Wall', 'Beijing'] },
        { id: 'pl52', emojis: ['🐘', '🕌'], answer: 'India', hints: ['Taj Mahal', 'Elephant', 'Curry'] },
        { id: 'pl53', emojis: ['🦁', '🌍'], answer: 'Africa', hints: ['Safari', 'Lions', 'Continent'] },
        { id: 'pl54', emojis: ['🐪', '🏜️'], answer: 'Egypt', hints: ['Pyramids', 'Sahara', 'Nile'] },
        { id: 'pl55', emojis: ['🦒', '🐆'], answer: 'Kenya', hints: ['Safari', 'Africa', 'Nairobi'] },
        { id: 'pl56', emojis: ['🐧', '❄️'], answer: 'Antarctica', hints: ['Penguins', 'Ice', 'South Pole'] },
        { id: 'pl57', emojis: ['🏔️', '🧗'], answer: 'Nepal', hints: ['Everest', 'Himalayas', 'Kathmandu'] },
        { id: 'pl58', emojis: ['🦥', '🌴'], answer: 'Costa Rica', hints: ['Rainforest', 'Sloths', 'Beaches'] },
    ],
    medium: [
        { id: 'pl59', emojis: ['🐪', '🏜️', '🔺'], answer: 'Egypt', hints: ['Pyramids', 'Nile', 'Pharaoh'] },
        { id: 'pl60', emojis: ['🦁', '🌿', '🌍'], answer: 'Africa', hints: ['Continent', 'Safari', 'Wildlife'] },
        { id: 'pl61', emojis: ['❄️', '🐧'], answer: 'Antarctica', hints: ['Ice', 'South Pole', 'Cold'] },
        { id: 'pl62', emojis: ['🌸', '🏯'], answer: 'Tokyo', hints: ['Japan', 'Cherry', 'Blossom'] },
        { id: 'pl63', emojis: ['🏔️', '🧘'], answer: 'Tibet', hints: ['Himalayas', 'Buddhist', 'Mountain'] },
        { id: 'pl64', emojis: ['🌊', '🏄'], answer: 'Malibu', hints: ['Beach', 'California', 'Surf'] },
        { id: 'pl65', emojis: ['🇬🇧', '☔', '🫖'], answer: 'London', hints: ['UK', 'England', 'Big Ben'] },
        { id: 'pl66', emojis: ['🍕', '🚤'], answer: 'Venice', hints: ['Italy', 'Canals', 'Gondola'] },
        { id: 'pl67', emojis: ['🌵', '🤠'], answer: 'Texas', hints: ['USA', 'Cowboys', 'Big'] },
        { id: 'pl68', emojis: ['🎲', '🏝️'], answer: 'Monaco', hints: ['Casino', 'Mediterranean', 'F1'] },
        { id: 'pl69', emojis: ['🏖️', '🍹'], answer: 'Bahamas', hints: ['Caribbean', 'Islands', 'Resort'] },
        { id: 'pl70', emojis: ['🌋', '🏝️'], answer: 'Hawaii', hints: ['Volcanoes', 'Islands', 'Aloha'] },
        { id: 'pl71', emojis: ['🎭', '🥐'], answer: 'Paris', hints: ['France', 'Croissants', 'Art'] },
        { id: 'pl72', emojis: ['🌉', '🚃'], answer: 'San Francisco', hints: ['Cable Cars', 'Golden Gate', 'Bay'] },
        { id: 'pl73', emojis: ['🐉', '🏙️'], answer: 'Hong Kong', hints: ['China', 'Skyscrapers', 'Harbor'] },
        { id: 'pl74', emojis: ['🕌', '🏜️'], answer: 'Dubai', hints: ['UAE', 'Luxury', 'Burj Khalifa'] },
        { id: 'pl75', emojis: ['🎺', '🥁', '🇧🇷'], answer: 'Rio de Janeiro', hints: ['Brazil', 'Carnival', 'Beach'] },
        { id: 'pl76', emojis: ['🏛️', '🫒'], answer: 'Athens', hints: ['Greece', 'Acropolis', 'Ancient'] },
        { id: 'pl77', emojis: ['🌷', '🚲'], answer: 'Amsterdam', hints: ['Netherlands', 'Canals', 'Bikes'] },
        { id: 'pl78', emojis: ['🍷', '🏰'], answer: 'Bordeaux', hints: ['France', 'Wine', 'Vineyards'] },
        { id: 'pl79', emojis: ['⛩️', '🌸'], answer: 'Kyoto', hints: ['Japan', 'Temple', 'Traditional'] },
        { id: 'pl80', emojis: ['🦩', '🌴'], answer: 'Miami', hints: ['Florida', 'Beach', 'Art Deco'] },
        { id: 'pl81', emojis: ['🎡', '🇬🇧'], answer: 'London', hints: ['Eye', 'Thames', 'England'] },
        { id: 'pl82', emojis: ['🌃', '🗼'], answer: 'Tokyo', hints: ['Japan', 'Tower', 'Neon'] },
        { id: 'pl83', emojis: ['🏖️', '🌅'], answer: 'Bali', hints: ['Indonesia', 'Island', 'Paradise'] },
        { id: 'pl84', emojis: ['🎪', '🗼'], answer: 'Paris', hints: ['Eiffel Tower', 'France', 'Romance'] },
        { id: 'pl85', emojis: ['🏔️', '🛷'], answer: 'Alps', hints: ['Mountains', 'Skiing', 'Europe'] },
        { id: 'pl86', emojis: ['🌊', '🐋'], answer: 'Iceland', hints: ['Whales', 'Geysers', 'Northern Lights'] },
        { id: 'pl87', emojis: ['🎰', '🏜️'], answer: 'Las Vegas', hints: ['Nevada', 'Desert', 'Sin City'] },
        { id: 'pl88', emojis: ['🌸', '🎎'], answer: 'Japan', hints: ['Cherry Blossoms', 'Geisha', 'Tokyo'] },
        { id: 'pl89', emojis: ['🏄', '🦈'], answer: 'Australia', hints: ['Great Barrier Reef', 'Surfing', 'Sydney'] },
        { id: 'pl90', emojis: ['🏰', '🎢'], answer: 'Orlando', hints: ['Disney World', 'Theme Parks', 'Florida'] },
        { id: 'pl91', emojis: ['🎭', '🌆'], answer: 'New York', hints: ['Broadway', 'Manhattan', 'Times Square'] },
        { id: 'pl92', emojis: ['🏜️', '🐫'], answer: 'Morocco', hints: ['Sahara', 'Marrakech', 'Africa'] },
        { id: 'pl93', emojis: ['🌴', '🎸'], answer: 'Jamaica', hints: ['Reggae', 'Caribbean', 'Bob Marley'] },
        { id: 'pl94', emojis: ['🧘', '🕉️'], answer: 'India', hints: ['Yoga', 'Hindu', 'Temples'] },
        { id: 'pl95', emojis: ['🏯', '🗡️'], answer: 'Japan', hints: ['Samurai', 'Castle', 'Ninja'] },
        { id: 'pl96', emojis: ['🥘', '💃'], answer: 'Spain', hints: ['Paella', 'Flamenco', 'Barcelona'] },
        { id: 'pl97', emojis: ['🍣', '🏙️'], answer: 'Tokyo', hints: ['Sushi', 'Japan', 'Modern'] },
        { id: 'pl98', emojis: ['🎻', '🏛️'], answer: 'Vienna', hints: ['Austria', 'Mozart', 'Classical'] },
        { id: 'pl99', emojis: ['🏰', '👸'], answer: 'Scotland', hints: ['Castles', 'Highlands', 'Edinburgh'] },
        { id: 'pl100', emojis: ['🌊', '🐠'], answer: 'Great Barrier Reef', hints: ['Australia', 'Coral', 'Diving'] },
        { id: 'pl101', emojis: ['🎡', '🌸'], answer: 'Cherry Blossom Festival', hints: ['Spring', 'DC', 'Japan'] },
        { id: 'pl102', emojis: ['🗿', '🏝️'], answer: 'Easter Island', hints: ['Chile', 'Statues', 'Moai'] },
        { id: 'pl103', emojis: ['🌋', '🏝️'], answer: 'Iceland', hints: ['Volcanoes', 'Geysers', 'Fire and Ice'] },
        { id: 'pl104', emojis: ['🎰', '🎲', '🏖️'], answer: 'Monte Carlo', hints: ['Monaco', 'Casino', 'Luxury'] },
        { id: 'pl105', emojis: ['🍜', '🥢'], answer: 'Thailand', hints: ['Bangkok', 'Pad Thai', 'Buddhism'] },
        { id: 'pl106', emojis: ['🏔️', '🦙'], answer: 'Peru', hints: ['Machu Picchu', 'Andes', 'Llama'] },
        { id: 'pl107', emojis: ['🎭', '🥁'], answer: 'Brazil', hints: ['Carnival', 'Rio', 'Samba'] },
        { id: 'pl108', emojis: ['🐻', '🥶'], answer: 'Siberia', hints: ['Russia', 'Cold', 'Remote'] },
        { id: 'pl109', emojis: ['🏰', '👰'], answer: 'Cinderella Castle', hints: ['Disney', 'Magic Kingdom', 'Fairy Tale'] },
        { id: 'pl110', emojis: ['🗽', '🌃'], answer: 'New York City', hints: ['Statue of Liberty', 'Manhattan', 'Empire State'] },
        { id: 'pl111', emojis: ['🏝️', '🌺', '🎶'], answer: 'Fiji', hints: ['Islands', 'Pacific', 'Paradise'] },
        { id: 'pl112', emojis: ['🎿', '🏔️', '🇨🇭'], answer: 'Swiss Alps', hints: ['Skiing', 'Switzerland', 'Mountains'] },
        { id: 'pl113', emojis: ['🌊', '🐚'], answer: 'Maldives', hints: ['Islands', 'Indian Ocean', 'Resorts'] },
        { id: 'pl114', emojis: ['🏛️', '⚔️'], answer: 'Sparta', hints: ['Greece', 'Warriors', 'Ancient'] },
        { id: 'pl115', emojis: ['🐘', '🏛️'], answer: 'Thailand', hints: ['Elephants', 'Temples', 'Bangkok'] },
        { id: 'pl116', emojis: ['🎎', '🏯'], answer: 'Kyoto', hints: ['Geisha', 'Japan', 'Traditional'] },
        { id: 'pl117', emojis: ['🌵', '🎸'], answer: 'Austin', hints: ['Texas', 'Music', 'Weird'] },
    ],
    hard: [
        { id: 'pl118', emojis: ['🏔️', '🙏', '🕉️'], answer: 'Nepal', hints: ['Everest', 'Himalayas', 'Buddha'] },
        { id: 'pl119', emojis: ['🌋', '🏝️', '🌴'], answer: 'Bali', hints: ['Indonesia', 'Island', 'Paradise'] },
        { id: 'pl120', emojis: ['🦙', '🏔️'], answer: 'Peru', hints: ['Machu Picchu', 'Andes', 'Llama'] },
        { id: 'pl121', emojis: ['🕌', '🌙'], answer: 'Dubai', hints: ['UAE', 'Luxury', 'Desert'] },
        { id: 'pl122', emojis: ['🏛️', '🏺'], answer: 'Greece', hints: ['Athens', 'Ancient', 'Olympics'] },
        { id: 'pl123', emojis: ['🗻', '☀️', '🏖️'], answer: 'Cape Town', hints: ['South Africa', 'Table Mountain', 'Wine'] },
        { id: 'pl124', emojis: ['🌲', '🏔️', '🇳🇴'], answer: 'Norway', hints: ['Fjords', 'Vikings', 'Northern Lights'] },
        { id: 'pl125', emojis: ['🎭', '🌊', '🇦🇺'], answer: 'Sydney', hints: ['Opera House', 'Harbor', 'Australia'] },
        { id: 'pl126', emojis: ['🏙️', '🌃', '🇸🇬'], answer: 'Singapore', hints: ['City State', 'Gardens', 'Asia'] },
        { id: 'pl127', emojis: ['🎎', '🎏'], answer: 'Japan', hints: ['Dolls', 'Kites', 'Culture'] },
        { id: 'pl128', emojis: ['🐉', '🏮'], answer: 'China', hints: ['Dragon', 'Lanterns', 'Beijing'] },
        { id: 'pl129', emojis: ['🌸', '🗻'], answer: 'Mount Fuji', hints: ['Japan', 'Volcano', 'Cherry Blossoms'] },
        { id: 'pl130', emojis: ['🏜️', '⭐'], answer: 'Sahara', hints: ['Desert', 'Africa', 'Sand'] },
        { id: 'pl131', emojis: ['🗿', '🇨🇱'], answer: 'Easter Island', hints: ['Moai', 'Chile', 'Pacific'] },
        { id: 'pl132', emojis: ['🌊', '🦈', '🏊'], answer: 'Great White', hints: ['South Africa', 'Cage Diving', 'Sharks'] },
        { id: 'pl133', emojis: ['🏔️', '🧊', '🇦🇷'], answer: 'Patagonia', hints: ['Argentina', 'Glaciers', 'Chile'] },
        { id: 'pl134', emojis: ['🌺', '🎶', '🇭🇺'], answer: 'Budapest', hints: ['Hungary', 'Danube', 'Baths'] },
        { id: 'pl135', emojis: ['🏰', '🧛'], answer: 'Transylvania', hints: ['Romania', 'Dracula', 'Castle'] },
        { id: 'pl136', emojis: ['🌌', '🏜️'], answer: 'Atacama', hints: ['Chile', 'Desert', 'Stars'] },
        { id: 'pl137', emojis: ['🦁', '🐃'], answer: 'Serengeti', hints: ['Tanzania', 'Safari', 'Migration'] },
        { id: 'pl138', emojis: ['🏛️', '📜'], answer: 'Alexandria', hints: ['Egypt', 'Library', 'Ancient'] },
        { id: 'pl139', emojis: ['🌊', '🐢'], answer: 'Galapagos', hints: ['Ecuador', 'Darwin', 'Islands'] },
        { id: 'pl140', emojis: ['🏔️', '🧗', '🇳🇵'], answer: 'Mount Everest', hints: ['Nepal', 'Highest', 'Climbing'] },
        { id: 'pl141', emojis: ['🌊', '🏊', '🇬🇷'], answer: 'Santorini', hints: ['Greece', 'Blue Domes', 'Island'] },
        { id: 'pl142', emojis: ['🏰', '🎭', '🇨🇿'], answer: 'Prague', hints: ['Czech', 'Castle', 'Bridge'] },
        { id: 'pl143', emojis: ['🎨', '🌷', '🇳🇱'], answer: 'Amsterdam', hints: ['Van Gogh', 'Tulips', 'Netherlands'] },
        { id: 'pl144', emojis: ['🕌', '🏜️', '🇲🇦'], answer: 'Marrakech', hints: ['Morocco', 'Medina', 'Souks'] },
        { id: 'pl145', emojis: ['🏛️', '🍕', '🇮🇹'], answer: 'Florence', hints: ['Italy', 'Renaissance', 'Art'] },
        { id: 'pl146', emojis: ['🎭', '🎬', '🇫🇷'], answer: 'Cannes', hints: ['France', 'Film Festival', 'Riviera'] },
        { id: 'pl147', emojis: ['🏔️', '⛷️', '🇫🇷'], answer: 'Chamonix', hints: ['France', 'Mont Blanc', 'Skiing'] },
        { id: 'pl148', emojis: ['🌴', '🎰', '🇲🇨'], answer: 'Monaco', hints: ['Casino', 'F1', 'Rich'] },
        { id: 'pl149', emojis: ['🏝️', '🌅', '🇹🇭'], answer: 'Phuket', hints: ['Thailand', 'Beach', 'Islands'] },
        { id: 'pl150', emojis: ['🏯', '🗡️', '🇯🇵'], answer: 'Osaka', hints: ['Japan', 'Castle', 'Food'] },
        { id: 'pl151', emojis: ['🎺', '🥁', '🇨🇺'], answer: 'Havana', hints: ['Cuba', 'Music', 'Classic Cars'] },
        { id: 'pl152', emojis: ['🏔️', '🚂', '🇵🇪'], answer: 'Machu Picchu', hints: ['Peru', 'Inca', 'Train'] },
        { id: 'pl153', emojis: ['🌊', '🐳', '🇮🇸'], answer: 'Iceland', hints: ['Whales', 'Geysers', 'Cold'] },
        { id: 'pl154', emojis: ['🏛️', '🎭', '🇷🇺'], answer: 'Moscow', hints: ['Russia', 'Kremlin', 'Red Square'] },
        { id: 'pl155', emojis: ['🌃', '🎰', '🇨🇳'], answer: 'Macau', hints: ['China', 'Casino', 'Portuguese'] },
        { id: 'pl156', emojis: ['🏝️', '🐟', '🇲🇻'], answer: 'Maldives', hints: ['Islands', 'Resorts', 'Indian Ocean'] },
        { id: 'pl157', emojis: ['🌸', '🏯', '🇰🇷'], answer: 'Seoul', hints: ['South Korea', 'Palaces', 'K-Pop'] },
        { id: 'pl158', emojis: ['🏔️', '🦅', '🇵🇰'], answer: 'K2', hints: ['Pakistan', 'Mountain', 'Second Highest'] },
        { id: 'pl159', emojis: ['🌊', '🏄', '🇵🇹'], answer: 'Portugal', hints: ['Surfing', 'Lisbon', 'Fado'] },
        { id: 'pl160', emojis: ['🎭', '🏛️', '🇦🇹'], answer: 'Vienna', hints: ['Austria', 'Opera', 'Mozart'] },
        { id: 'pl161', emojis: ['🏜️', '🐫', '🇯🇴'], answer: 'Petra', hints: ['Jordan', 'Rose City', 'Ancient'] },
        { id: 'pl162', emojis: ['🌲', '🦌', '🇫🇮'], answer: 'Finland', hints: ['Lapland', 'Reindeer', 'Sauna'] },
        { id: 'pl163', emojis: ['🏰', '🌹', '🇬🇧'], answer: 'England', hints: ['Castles', 'Royalty', 'Gardens'] },
        { id: 'pl164', emojis: ['🌴', '🥥', '🇵🇭'], answer: 'Philippines', hints: ['Islands', 'Beaches', 'Tropical'] },
        { id: 'pl165', emojis: ['🎺', '🎭', '🇦🇷'], answer: 'Buenos Aires', hints: ['Argentina', 'Tango', 'Culture'] },
        { id: 'pl166', emojis: ['🏔️', '🏕️', '🇨🇦'], answer: 'Banff', hints: ['Canada', 'National Park', 'Rockies'] },
        { id: 'pl167', emojis: ['🌊', '🌅', '🇬🇷'], answer: 'Mykonos', hints: ['Greece', 'Island', 'Party'] },
        { id: 'pl168', emojis: ['🏛️', '🎭', '🇹🇷'], answer: 'Istanbul', hints: ['Turkey', 'Hagia Sophia', 'Bosphorus'] },
        { id: 'pl169', emojis: ['🌲', '🏔️', '🇳🇿'], answer: 'New Zealand', hints: ['Lord of the Rings', 'Mountains', 'Kiwi'] },
        { id: 'pl170', emojis: ['🏜️', '🌵', '🇺🇸'], answer: 'Death Valley', hints: ['California', 'Hot', 'Desert'] },
        { id: 'pl171', emojis: ['🌊', '🐋', '🇿🇦'], answer: 'Hermanus', hints: ['South Africa', 'Whale Watching', 'Coast'] },
        { id: 'pl172', emojis: ['🏔️', '⛩️', '🇯🇵'], answer: 'Hakone', hints: ['Japan', 'Hot Springs', 'Fuji View'] },
        { id: 'pl173', emojis: ['🎪', '🎭', '🇺🇸'], answer: 'Cirque du Soleil', hints: ['Vegas', 'Circus', 'Entertainment'] },
        { id: 'pl174', emojis: ['🌋', '🌲', '🇨🇷'], answer: 'Costa Rica', hints: ['Volcanoes', 'Rainforest', 'Pura Vida'] },
        { id: 'pl175', emojis: ['🏝️', '🌺', '🇹🇭'], answer: 'Koh Samui', hints: ['Thailand', 'Island', 'Beach'] },
    ],
};

window.PLACE_PUZZLES = PLACE_PUZZLES;
