/**
 * Song Puzzles - 200 puzzles
 */
const SONG_PUZZLES = {
    easy: [
        { id: 's1', emojis: ['💍', '👩', '👩', '👩'], answer: 'Single Ladies', hints: ['Beyonce', 'Ring', 'Dance'] },
        { id: 's2', emojis: ['🌧️', '💜'], answer: 'Purple Rain', hints: ['Prince', '80s', 'Iconic'] },
        { id: 's3', emojis: ['🌙', '💃'], answer: 'Dancing in the Moonlight', hints: ['Classic', '70s', 'Night'] },
        { id: 's4', emojis: ['🔨', '⏰'], answer: 'Hammer Time', hints: ['MC Hammer', '90s', 'Cant Touch This'] },
        { id: 's5', emojis: ['🔥', '🏠'], answer: 'Burning Down the House', hints: ['Talking Heads', '80s', 'Rock'] },
        { id: 's6', emojis: ['🪜', '😇'], answer: 'Stairway to Heaven', hints: ['Led Zeppelin', 'Classic', 'Rock'] },
        { id: 's7', emojis: ['👁️', '🐯'], answer: 'Eye of the Tiger', hints: ['Survivor', 'Rocky', '80s'] },
        { id: 's8', emojis: ['💛', '🚕'], answer: 'Big Yellow Taxi', hints: ['Joni Mitchell', 'Folk', 'Paradise'] },
        { id: 's9', emojis: ['🌈', '☁️'], answer: 'Somewhere Over the Rainbow', hints: ['Wizard of Oz', 'Classic', 'Judy'] },
        { id: 's10', emojis: ['🎉', '🇺🇸'], answer: 'Party in the USA', hints: ['Miley Cyrus', 'Pop', 'LA'] },
        { id: 's11', emojis: ['👋', '☀️'], answer: 'Here Comes the Sun', hints: ['Beatles', '60s', 'Classic'] },
        { id: 's12', emojis: ['💎', '🌌'], answer: 'Diamonds', hints: ['Rihanna', 'Sky', 'Pop'] },
        { id: 's13', emojis: ['🛣️', '🚗'], answer: 'Life is a Highway', hints: ['Cars', 'Rascal Flatts', 'Country'] },
        { id: 's14', emojis: ['💃', '👑'], answer: 'Dancing Queen', hints: ['ABBA', '70s', 'Disco'] },
        { id: 's15', emojis: ['🔔', '🎄'], answer: 'Jingle Bells', hints: ['Christmas', 'Classic', 'Holiday'] },
        { id: 's16', emojis: ['❤️', '💔'], answer: 'Heartbreak Hotel', hints: ['Elvis', '50s', 'Rock'] },
        { id: 's17', emojis: ['🌞', '😊'], answer: 'Walking on Sunshine', hints: ['Katrina', '80s', 'Happy'] },
        { id: 's18', emojis: ['🎸', '🦸'], answer: 'Guitar Hero', hints: ['Video Game', 'Rock', 'Music'] },
        { id: 's19', emojis: ['💜', '🌧️'], answer: 'Purple Rain', hints: ['Prince', 'Ballad', 'Classic'] },
        { id: 's20', emojis: ['🚗', '🌅'], answer: 'Drive', hints: ['The Cars', '80s', 'Synth'] },
        { id: 's21', emojis: ['🎅', '🏘️'], answer: 'Santa Claus is Coming to Town', hints: ['Christmas', 'Holiday', 'Classic'] },
        { id: 's22', emojis: ['⭐', '✨'], answer: 'Starlight', hints: ['Muse', 'Rock', '2000s'] },
        { id: 's23', emojis: ['🌊', '👀'], answer: 'Ocean Eyes', hints: ['Billie Eilish', 'Pop', 'Debut'] },
        { id: 's24', emojis: ['☀️', '🕶️'], answer: 'Sunglasses at Night', hints: ['Corey Hart', '80s', 'Synth'] },
        { id: 's25', emojis: ['💋', '👸'], answer: 'Kiss', hints: ['Prince', '80s', 'Pop'] },
        { id: 's26', emojis: ['🎤', '⭐'], answer: 'Superstar', hints: ['Carpenters', '70s', 'Ballad'] },
        { id: 's27', emojis: ['🌙', '🚶'], answer: 'Walking on the Moon', hints: ['The Police', 'Sting', '80s'] },
        { id: 's28', emojis: ['❤️', '🔥'], answer: 'Burning Love', hints: ['Elvis', 'Classic', 'Rock'] },
        { id: 's29', emojis: ['🎂', '🎉'], answer: 'Birthday', hints: ['Beatles', 'Celebration', 'Classic'] },
        { id: 's30', emojis: ['🌹', '🎸'], answer: 'Guns N Roses', hints: ['Band', 'Rock', 'Axl'] },
        { id: 's31', emojis: ['👟', '💃'], answer: 'Footloose', hints: ['Kenny Loggins', '80s', 'Movie'] },
        { id: 's32', emojis: ['🚀', '👨'], answer: 'Rocket Man', hints: ['Elton John', '70s', 'Space'] },
        { id: 's33', emojis: ['😊', '🎵'], answer: 'Happy', hints: ['Pharrell', 'Pop', 'Despicable Me'] },
        { id: 's34', emojis: ['🔔', '🔔', '🔔'], answer: 'Hells Bells', hints: ['AC/DC', 'Rock', 'Heavy'] },
        { id: 's35', emojis: ['🌙', '💙'], answer: 'Blue Moon', hints: ['Classic', 'Jazz', 'Standard'] },
        { id: 's36', emojis: ['💃', '🌃'], answer: 'Dancing in the Dark', hints: ['Springsteen', '80s', 'Rock'] },
        { id: 's37', emojis: ['🎄', '🏠'], answer: 'Ill Be Home for Christmas', hints: ['Holiday', 'Classic', 'Bing'] },
        { id: 's38', emojis: ['❄️', '⛄'], answer: 'Let It Snow', hints: ['Christmas', 'Winter', 'Classic'] },
        { id: 's39', emojis: ['🎁', '🎄'], answer: 'All I Want for Christmas Is You', hints: ['Mariah Carey', 'Holiday', 'Pop'] },
        { id: 's40', emojis: ['🦌', '🔴'], answer: 'Rudolph the Red-Nosed Reindeer', hints: ['Christmas', 'Classic', 'Holiday'] },
        { id: 's41', emojis: ['👀', '🐯'], answer: 'Eye of the Tiger', hints: ['Survivor', 'Rocky III', 'Motivation'] },
        { id: 's42', emojis: ['🌅', '🏃'], answer: 'Running', hints: ['Various', 'Pop', 'Exercise'] },
        { id: 's43', emojis: ['🎸', '😭'], answer: 'While My Guitar Gently Weeps', hints: ['Beatles', 'Harrison', 'Classic'] },
        { id: 's44', emojis: ['💔', '🏨'], answer: 'Heartbreak Hotel', hints: ['Elvis Presley', 'Rock', '50s'] },
        { id: 's45', emojis: ['⚡', '👦'], answer: 'Electric Youth', hints: ['Debbie Gibson', '80s', 'Pop'] },
        { id: 's46', emojis: ['🌊', '🏄'], answer: 'Surfin USA', hints: ['Beach Boys', '60s', 'Summer'] },
        { id: 's47', emojis: ['🎤', '💃'], answer: 'Vogue', hints: ['Madonna', '90s', 'Dance'] },
        { id: 's48', emojis: ['🔥', '🎶'], answer: 'We Didnt Start the Fire', hints: ['Billy Joel', '80s', 'History'] },
        { id: 's49', emojis: ['👸', '🎤'], answer: 'Queen', hints: ['Band', 'Rock', 'Freddie'] },
        { id: 's50', emojis: ['🌍', '🎵'], answer: 'We Are the World', hints: ['USA for Africa', '80s', 'Charity'] },
        { id: 's51', emojis: ['💪', '💥'], answer: 'Stronger', hints: ['Kanye', 'Daft Punk', 'Hip Hop'] },
        { id: 's52', emojis: ['🎹', '👨'], answer: 'Piano Man', hints: ['Billy Joel', '70s', 'Classic'] },
        { id: 's53', emojis: ['🌧️', '😢'], answer: 'Crying in the Rain', hints: ['A-ha', '80s', 'Pop'] },
        { id: 's54', emojis: ['🏠', '🌅'], answer: 'Take Me Home Tonight', hints: ['Eddie Money', '80s', 'Rock'] },
        { id: 's55', emojis: ['🎉', '🎊'], answer: 'Celebration', hints: ['Kool and the Gang', '80s', 'Disco'] },
        { id: 's56', emojis: ['👋', '👋'], answer: 'Bye Bye Bye', hints: ['NSYNC', '90s', 'Pop'] },
        { id: 's57', emojis: ['💃', '💃'], answer: 'Dancing with Myself', hints: ['Billy Idol', '80s', 'Rock'] },
        { id: 's58', emojis: ['🌙', '⭐'], answer: 'Fly Me to the Moon', hints: ['Sinatra', 'Jazz', 'Classic'] },
        { id: 's59', emojis: ['❤️', '🗡️'], answer: 'Love Hurts', hints: ['Nazareth', '70s', 'Rock'] },
        { id: 's60', emojis: ['🎤', '⭐', '🌟'], answer: 'A Star Is Born', hints: ['Lady Gaga', 'Shallow', 'Movie'] },
        { id: 's61', emojis: ['🚂', '🎵'], answer: 'Crazy Train', hints: ['Ozzy', 'Metal', '80s'] },
        { id: 's62', emojis: ['👻', '👻'], answer: 'Ghostbusters', hints: ['Ray Parker Jr', '80s', 'Movie'] },
        { id: 's63', emojis: ['🌈', '🎨'], answer: 'True Colors', hints: ['Cyndi Lauper', '80s', 'Ballad'] },
        { id: 's64', emojis: ['🛤️', '🌅'], answer: 'On the Road Again', hints: ['Willie Nelson', 'Country', 'Classic'] },
        { id: 's65', emojis: ['👯', '💃'], answer: 'Girls Just Want to Have Fun', hints: ['Cyndi Lauper', '80s', 'Pop'] },
    ],
    medium: [
        { id: 's66', emojis: ['🦋', '💔'], answer: 'Butterflies', hints: ['Kacey Musgraves', 'Country', 'Love'] },
        { id: 's67', emojis: ['🍾', '⬆️'], answer: 'Champagne Supernova', hints: ['Oasis', 'Britpop', '90s'] },
        { id: 's68', emojis: ['🔥', '💧'], answer: 'Fire and Rain', hints: ['James Taylor', '70s', 'Folk'] },
        { id: 's69', emojis: ['🎪', '🎭'], answer: 'The Show Must Go On', hints: ['Queen', 'Freddie', 'Epic'] },
        { id: 's70', emojis: ['⭐', '💛'], answer: 'Yellow', hints: ['Coldplay', '2000s', 'Stars'] },
        { id: 's71', emojis: ['🔥', '🎸'], answer: 'Through the Fire and Flames', hints: ['Dragonforce', 'Metal', 'Guitar Hero'] },
        { id: 's72', emojis: ['😋', '🐺'], answer: 'Hungry Like the Wolf', hints: ['Duran Duran', '80s', 'Pop'] },
        { id: 's73', emojis: ['🏠', '🌅'], answer: 'The House of the Rising Sun', hints: ['Animals', '60s', 'Classic'] },
        { id: 's74', emojis: ['📹', '🔪', '📻', '⭐'], answer: 'Video Killed the Radio Star', hints: ['Buggles', 'MTV', '80s'] },
        { id: 's75', emojis: ['🧱', '🧱', '🧱'], answer: 'Another Brick in the Wall', hints: ['Pink Floyd', '70s', 'Education'] },
        { id: 's76', emojis: ['🎤', '🌧️'], answer: 'Singing in the Rain', hints: ['Musical', 'Classic', 'Hollywood'] },
        { id: 's77', emojis: ['👶', '🔙', '🕐'], answer: 'Baby One More Time', hints: ['Britney Spears', '90s', 'Pop'] },
        { id: 's78', emojis: ['🔄', '🌊'], answer: 'Rolling in the Deep', hints: ['Adele', '2010s', 'Soul'] },
        { id: 's79', emojis: ['🦅', '🏨'], answer: 'Hotel California', hints: ['Eagles', '70s', 'Classic Rock'] },
        { id: 's80', emojis: ['💫', '🎵'], answer: 'Bohemian Rhapsody', hints: ['Queen', 'Freddie', 'Opera'] },
        { id: 's81', emojis: ['🎵', '🔇'], answer: 'The Sound of Silence', hints: ['Simon and Garfunkel', '60s', 'Folk'] },
        { id: 's82', emojis: ['🎸', '🌟', '🎤'], answer: 'Rock Star', hints: ['Post Malone', 'Hip Hop', '2017'] },
        { id: 's83', emojis: ['🌙', '🌊'], answer: 'Moonlight Sonata', hints: ['Beethoven', 'Classical', 'Piano'] },
        { id: 's84', emojis: ['🏃', '👟'], answer: 'Run', hints: ['Snow Patrol', '2000s', 'Rock'] },
        { id: 's85', emojis: ['💔', '💔'], answer: 'Unbreak My Heart', hints: ['Toni Braxton', '90s', 'R&B'] },
        { id: 's86', emojis: ['🌧️', '☔'], answer: 'Umbrella', hints: ['Rihanna', '2000s', 'Pop'] },
        { id: 's87', emojis: ['🔥', '🔥', '🔥'], answer: 'Ring of Fire', hints: ['Johnny Cash', 'Country', 'Classic'] },
        { id: 's88', emojis: ['🌙', '😴'], answer: 'Mr Sandman', hints: ['Chordettes', '50s', 'Classic'] },
        { id: 's89', emojis: ['🎭', '🎤'], answer: 'The Sound of Music', hints: ['Musical', 'Julie Andrews', 'Classic'] },
        { id: 's90', emojis: ['💃', '🕺', '🎵'], answer: 'Uptown Funk', hints: ['Bruno Mars', '2010s', 'Funk'] },
        { id: 's91', emojis: ['🌹', '💔'], answer: 'Every Rose Has Its Thorn', hints: ['Poison', '80s', 'Rock'] },
        { id: 's92', emojis: ['🚗', '🎵'], answer: 'Drive', hints: ['Incubus', '2000s', 'Rock'] },
        { id: 's93', emojis: ['💃', '🌟'], answer: 'Gonna Make You a Star', hints: ['David Essex', '70s', 'Pop'] },
        { id: 's94', emojis: ['🌍', '🔥'], answer: 'Set Fire to the Rain', hints: ['Adele', '2010s', 'Pop'] },
        { id: 's95', emojis: ['💜', '☔'], answer: 'Purple Rain', hints: ['Prince', 'Rock', 'Ballad'] },
        { id: 's96', emojis: ['🚶', '🔥'], answer: 'Walk Through Fire', hints: ['Various', 'Pop', 'Ballad'] },
        { id: 's97', emojis: ['🎺', '🌙'], answer: 'Fly Me to the Moon', hints: ['Frank Sinatra', 'Jazz', 'Standard'] },
        { id: 's98', emojis: ['💃', '💕'], answer: 'Crazy in Love', hints: ['Beyonce', '2000s', 'R&B'] },
        { id: 's99', emojis: ['🎹', '🔥'], answer: 'Great Balls of Fire', hints: ['Jerry Lee Lewis', '50s', 'Rock'] },
        { id: 's100', emojis: ['🌊', '🎵'], answer: 'Under the Sea', hints: ['Little Mermaid', 'Disney', 'Musical'] },
        { id: 's101', emojis: ['🌙', '😊'], answer: 'Moonlight', hints: ['Various', 'Pop', 'Romantic'] },
        { id: 's102', emojis: ['🎄', '💚'], answer: 'Youre a Mean One Mr Grinch', hints: ['Christmas', 'Dr Seuss', 'Holiday'] },
        { id: 's103', emojis: ['🔔', '😇'], answer: 'Halo', hints: ['Beyonce', '2000s', 'Pop'] },
        { id: 's104', emojis: ['❤️', '🔓'], answer: 'Locked Out of Heaven', hints: ['Bruno Mars', '2010s', 'Pop'] },
        { id: 's105', emojis: ['🎸', '⚡'], answer: 'Thunderstruck', hints: ['AC/DC', 'Rock', '90s'] },
        { id: 's106', emojis: ['🌺', '🎶'], answer: 'Lei', hints: ['Hawaii', 'Traditional', 'Island'] },
        { id: 's107', emojis: ['🎉', '🏠'], answer: 'Our House', hints: ['Madness', '80s', 'Pop'] },
        { id: 's108', emojis: ['🕺', '👑'], answer: 'Billie Jean', hints: ['Michael Jackson', '80s', 'Pop'] },
        { id: 's109', emojis: ['👻', '🎤'], answer: 'Somebody That I Used to Know', hints: ['Gotye', '2010s', 'Pop'] },
        { id: 's110', emojis: ['🌧️', '👨'], answer: 'Raindrops Keep Falling on My Head', hints: ['BJ Thomas', '60s', 'Classic'] },
        { id: 's111', emojis: ['🚶', '☀️'], answer: 'Walking on Sunshine', hints: ['Katrina', '80s', 'Pop'] },
        { id: 's112', emojis: ['💰', '💰', '💰'], answer: 'Money Money Money', hints: ['ABBA', '70s', 'Pop'] },
        { id: 's113', emojis: ['🎸', '🎵', '🔥'], answer: 'Smoke on the Water', hints: ['Deep Purple', '70s', 'Rock'] },
        { id: 's114', emojis: ['🏃', '🌍'], answer: 'Running Up That Hill', hints: ['Kate Bush', '80s', 'Stranger Things'] },
        { id: 's115', emojis: ['🎹', '🌃'], answer: 'New York State of Mind', hints: ['Billy Joel', '70s', 'Jazz'] },
        { id: 's116', emojis: ['🌙', '☀️'], answer: 'Here Comes the Sun', hints: ['Beatles', 'Abbey Road', '60s'] },
        { id: 's117', emojis: ['🎸', '🎤', '⭐'], answer: 'Born to Be Wild', hints: ['Steppenwolf', '60s', 'Rock'] },
        { id: 's118', emojis: ['❤️', '📝'], answer: 'Love Letter', hints: ['Various', 'Pop', 'Ballad'] },
        { id: 's119', emojis: ['🌊', '👁️'], answer: 'Ocean Eyes', hints: ['Billie Eilish', 'Pop', 'Debut'] },
        { id: 's120', emojis: ['💃', '🌃', '⭐'], answer: 'Stayin Alive', hints: ['Bee Gees', '70s', 'Disco'] },
        { id: 's121', emojis: ['🎵', '💕'], answer: 'Cant Help Falling in Love', hints: ['Elvis', '60s', 'Classic'] },
        { id: 's122', emojis: ['🌈', '🌟'], answer: 'Rainbow Connection', hints: ['Kermit', 'Muppets', 'Classic'] },
        { id: 's123', emojis: ['🔥', '👧'], answer: 'Girl on Fire', hints: ['Alicia Keys', '2010s', 'Pop'] },
        { id: 's124', emojis: ['💎', '💎'], answer: 'Lucy in the Sky with Diamonds', hints: ['Beatles', '60s', 'Psychedelic'] },
        { id: 's125', emojis: ['🎤', '🌙', '⭐'], answer: 'Fly Me to the Moon', hints: ['Sinatra', 'Jazz', 'Classic'] },
        { id: 's126', emojis: ['🏃', '🏃', '🏃'], answer: 'Run the World', hints: ['Beyonce', '2010s', 'Empowerment'] },
        { id: 's127', emojis: ['🌙', '🚶'], answer: 'Moondance', hints: ['Van Morrison', '70s', 'Jazz'] },
        { id: 's128', emojis: ['🎺', '☀️'], answer: 'Good Morning', hints: ['Singin in the Rain', 'Musical', 'Classic'] },
        { id: 's129', emojis: ['💔', '🎵'], answer: 'Heartbreak Song', hints: ['Various', 'Pop', 'Ballad'] },
        { id: 's130', emojis: ['🎸', '😈'], answer: 'Highway to Hell', hints: ['AC/DC', 'Rock', '70s'] },
    ],
    hard: [
        { id: 's131', emojis: ['🎸', '🌧️', '👨'], answer: 'Purple Haze', hints: ['Jimi Hendrix', '60s', 'Rock'] },
        { id: 's132', emojis: ['🧱', '💔'], answer: 'The Wall', hints: ['Pink Floyd', '70s', 'Rock Opera'] },
        { id: 's133', emojis: ['🎭', '😢', '🤡'], answer: 'Tears of a Clown', hints: ['Smokey Robinson', '60s', 'Motown'] },
        { id: 's134', emojis: ['🌌', '👨', '🎸'], answer: 'Space Oddity', hints: ['David Bowie', '60s', 'Glam'] },
        { id: 's135', emojis: ['🔔', '📖', '❓'], answer: 'For Whom the Bell Tolls', hints: ['Metallica', 'Metal', '80s'] },
        { id: 's136', emojis: ['🎹', '🌧️', '💔'], answer: 'November Rain', hints: ['Guns N Roses', '90s', 'Rock'] },
        { id: 's137', emojis: ['🌊', '💎', '🌅'], answer: 'Shine on You Crazy Diamond', hints: ['Pink Floyd', '70s', 'Syd'] },
        { id: 's138', emojis: ['⚡', '👦', '🎸'], answer: 'Johnny B Goode', hints: ['Chuck Berry', '50s', 'Rock'] },
        { id: 's139', emojis: ['🎭', '🌌', '✨'], answer: 'Life on Mars', hints: ['David Bowie', '70s', 'Glam'] },
        { id: 's140', emojis: ['🔔', '🔔', '💀'], answer: 'Hells Bells', hints: ['AC/DC', '80s', 'Rock'] },
        { id: 's141', emojis: ['🎤', '🌃', '🎷'], answer: 'Careless Whisper', hints: ['George Michael', '80s', 'Pop'] },
        { id: 's142', emojis: ['💀', '🎵', '🖤'], answer: 'Fade to Black', hints: ['Metallica', 'Metal', '80s'] },
        { id: 's143', emojis: ['🌈', '🌧️', '☀️'], answer: 'After the Storm', hints: ['Kali Uchis', '2010s', 'R&B'] },
        { id: 's144', emojis: ['🚂', '🎵', '💨'], answer: 'Peace Train', hints: ['Cat Stevens', '70s', 'Folk'] },
        { id: 's145', emojis: ['🎭', '🎪', '👨'], answer: 'The Man Who Sold the World', hints: ['Bowie', '70s', 'Nirvana Cover'] },
        { id: 's146', emojis: ['🌙', '🔮', '✨'], answer: 'Black Magic Woman', hints: ['Santana', '70s', 'Rock'] },
        { id: 's147', emojis: ['🎸', '🌃', '🎵'], answer: 'Sultans of Swing', hints: ['Dire Straits', '70s', 'Rock'] },
        { id: 's148', emojis: ['💜', '💨', '🎸'], answer: 'Smoke on the Water', hints: ['Deep Purple', '70s', 'Riff'] },
        { id: 's149', emojis: ['🎺', '🎷', '🌃'], answer: 'Caravan', hints: ['Duke Ellington', 'Jazz', 'Classic'] },
        { id: 's150', emojis: ['🌙', '👁️', '🔮'], answer: 'Crystal Ball', hints: ['Various', 'Rock', '70s'] },
        { id: 's151', emojis: ['🎹', '💀', '🎵'], answer: 'A Day in the Life', hints: ['Beatles', '60s', 'Sgt Pepper'] },
        { id: 's152', emojis: ['🌊', '🌊', '🌊'], answer: 'Waves', hints: ['Various', 'Electronic', '2010s'] },
        { id: 's153', emojis: ['🔥', '🎸', '⚡'], answer: 'Fire', hints: ['Jimi Hendrix', '60s', 'Rock'] },
        { id: 's154', emojis: ['🎭', '🎬', '🎵'], answer: 'The Show Must Go On', hints: ['Queen', '90s', 'Final'] },
        { id: 's155', emojis: ['🌙', '🎷', '💙'], answer: 'Blue Moon', hints: ['Standard', 'Jazz', 'Classic'] },
        { id: 's156', emojis: ['🚶', '🌧️', '💔'], answer: 'November Rain', hints: ['GNR', 'Rock', 'Ballad'] },
        { id: 's157', emojis: ['🎹', '🌌', '✨'], answer: 'Rocket Man', hints: ['Elton John', '70s', 'Classic'] },
        { id: 's158', emojis: ['⚔️', '🛡️', '🎵'], answer: 'Knights of Cydonia', hints: ['Muse', '2000s', 'Rock'] },
        { id: 's159', emojis: ['🌅', '🎸', '🏖️'], answer: 'Wish You Were Here', hints: ['Pink Floyd', '70s', 'Tribute'] },
        { id: 's160', emojis: ['🎤', '💎', '✨'], answer: 'Shine', hints: ['Various', 'Pop', '2000s'] },
        { id: 's161', emojis: ['🐦', '🎵', '🆓'], answer: 'Free Bird', hints: ['Lynyrd Skynyrd', '70s', 'Southern'] },
        { id: 's162', emojis: ['🎸', '😇', '👼'], answer: 'Angel', hints: ['Various', 'Rock', 'Ballad'] },
        { id: 's163', emojis: ['🌌', '🔮', '👁️'], answer: 'Superstition', hints: ['Stevie Wonder', '70s', 'Funk'] },
        { id: 's164', emojis: ['🎹', '🌃', '🗽'], answer: 'New York New York', hints: ['Sinatra', 'Classic', 'Jazz'] },
        { id: 's165', emojis: ['⚡', '👨', '🎸'], answer: 'Voodoo Child', hints: ['Jimi Hendrix', '60s', 'Rock'] },
        { id: 's166', emojis: ['🌧️', '💜', '🎸'], answer: 'Purple Rain', hints: ['Prince', '80s', 'Epic'] },
        { id: 's167', emojis: ['🎭', '🖤', '🎵'], answer: 'Black', hints: ['Pearl Jam', '90s', 'Grunge'] },
        { id: 's168', emojis: ['🌊', '🏊', '💙'], answer: 'Come Sail Away', hints: ['Styx', '70s', 'Rock'] },
        { id: 's169', emojis: ['🎺', '🌙', '⭐'], answer: 'Moonlight Serenade', hints: ['Glenn Miller', 'Jazz', 'Big Band'] },
        { id: 's170', emojis: ['🎸', '🔥', '👹'], answer: 'Sympathy for the Devil', hints: ['Rolling Stones', '60s', 'Rock'] },
        { id: 's171', emojis: ['🌈', '🌧️', '☀️'], answer: 'Rainbow', hints: ['Kacey Musgraves', 'Country', '2010s'] },
        { id: 's172', emojis: ['🎹', '🌃', '💔'], answer: 'Someone Like You', hints: ['Adele', '2010s', 'Ballad'] },
        { id: 's173', emojis: ['🚀', '👨', '🌌'], answer: 'Starman', hints: ['David Bowie', '70s', 'Glam'] },
        { id: 's174', emojis: ['🎸', '⚡', '🌩️'], answer: 'Ride the Lightning', hints: ['Metallica', 'Metal', '80s'] },
        { id: 's175', emojis: ['🎭', '😭', '🎵'], answer: 'Creep', hints: ['Radiohead', '90s', 'Alternative'] },
        { id: 's176', emojis: ['🎹', '🎵', '✨'], answer: 'Clair de Lune', hints: ['Debussy', 'Classical', 'Piano'] },
        { id: 's177', emojis: ['🎸', '🌌', '🔮'], answer: 'Comfortably Numb', hints: ['Pink Floyd', '70s', 'The Wall'] },
        { id: 's178', emojis: ['👻', '🎵', '🌃'], answer: 'Thriller', hints: ['Michael Jackson', '80s', 'Pop'] },
        { id: 's179', emojis: ['🎤', '💕', '🌹'], answer: 'Unchained Melody', hints: ['Righteous Brothers', '60s', 'Ghost'] },
        { id: 's180', emojis: ['🎸', '🌅', '🏖️'], answer: 'Hotel California', hints: ['Eagles', '70s', 'Classic'] },
        { id: 's181', emojis: ['⚡', '🎸', '💀'], answer: 'Enter Sandman', hints: ['Metallica', '90s', 'Metal'] },
        { id: 's182', emojis: ['🎹', '🌧️', '🎵'], answer: 'Rainy Days and Mondays', hints: ['Carpenters', '70s', 'Pop'] },
        { id: 's183', emojis: ['🚂', '🎵', '🌌'], answer: 'Midnight Train to Georgia', hints: ['Gladys Knight', '70s', 'Soul'] },
        { id: 's184', emojis: ['🎸', '🔥', '💔'], answer: 'Burning Heart', hints: ['Survivor', '80s', 'Rocky IV'] },
        { id: 's185', emojis: ['🌙', '🎷', '💕'], answer: 'In the Mood', hints: ['Glenn Miller', 'Jazz', 'Swing'] },
        { id: 's186', emojis: ['🎹', '✨', '🌌'], answer: 'Starlight', hints: ['Muse', '2000s', 'Rock'] },
        { id: 's187', emojis: ['🎤', '🌃', '🗽'], answer: 'Empire State of Mind', hints: ['Jay-Z', '2000s', 'Hip Hop'] },
        { id: 's188', emojis: ['🎸', '🌊', '🏄'], answer: 'Wipe Out', hints: ['Surfaris', '60s', 'Surf Rock'] },
        { id: 's189', emojis: ['🎹', '🎵', '💔'], answer: 'The Scientist', hints: ['Coldplay', '2000s', 'Alternative'] },
        { id: 's190', emojis: ['🔔', '🎵', '🙏'], answer: 'Amazing Grace', hints: ['Traditional', 'Hymn', 'Classic'] },
        { id: 's191', emojis: ['🎸', '⚡', '🌩️'], answer: 'Back in Black', hints: ['AC/DC', '80s', 'Rock'] },
        { id: 's192', emojis: ['🌙', '🎤', '💙'], answer: 'Feeling Good', hints: ['Nina Simone', 'Jazz', 'Classic'] },
        { id: 's193', emojis: ['🎹', '🌅', '✨'], answer: 'Golden Hour', hints: ['Kacey Musgraves', 'Country', '2010s'] },
        { id: 's194', emojis: ['🎸', '🔥', '🎵'], answer: 'Light My Fire', hints: ['The Doors', '60s', 'Rock'] },
        { id: 's195', emojis: ['🌊', '🎵', '💙'], answer: 'Beyond the Sea', hints: ['Bobby Darin', '50s', 'Classic'] },
        { id: 's196', emojis: ['🎤', '💕', '✨'], answer: 'At Last', hints: ['Etta James', '60s', 'Soul'] },
        { id: 's197', emojis: ['🎸', '🌃', '💔'], answer: 'Layla', hints: ['Eric Clapton', '70s', 'Rock'] },
        { id: 's198', emojis: ['🎹', '🌙', '🌌'], answer: 'Clair de Lune', hints: ['Debussy', 'Classical', 'Moon'] },
        { id: 's199', emojis: ['🚀', '🎵', '⭐'], answer: 'Starship', hints: ['Nicki Minaj', '2010s', 'Pop'] },
        { id: 's200', emojis: ['🎤', '👑', '💜'], answer: 'Royals', hints: ['Lorde', '2010s', 'Alternative'] },
    ],
};

window.SONG_PUZZLES = SONG_PUZZLES;
