/**
 * TV Show Puzzles - 200 puzzles
 */
const TVSHOW_PUZZLES = {
    easy: [
        { id: 't1', emojis: ['👨‍👩‍👧‍👦', '📺'], answer: 'Modern Family', hints: ['Comedy', 'ABC', 'Sitcom'] },
        { id: 't2', emojis: ['🐉', '🔥', '👑'], answer: 'Game of Thrones', hints: ['HBO', 'Fantasy', 'Winter'] },
        { id: 't3', emojis: ['🏢', '📋'], answer: 'The Office', hints: ['NBC', 'Dunder', 'Comedy'] },
        { id: 't4', emojis: ['👫', '☕'], answer: 'Friends', hints: ['NBC', 'Central Perk', 'Sitcom'] },
        { id: 't5', emojis: ['👨‍🔬', '💊'], answer: 'Breaking Bad', hints: ['AMC', 'Meth', 'Walter'] },
        { id: 't6', emojis: ['🧟', '🚶'], answer: 'The Walking Dead', hints: ['AMC', 'Zombies', 'Apocalypse'] },
        { id: 't7', emojis: ['👽', '🚲', '👦'], answer: 'Stranger Things', hints: ['Netflix', 'Eleven', 'Hawkins'] },
        { id: 't8', emojis: ['👨‍👩‍👧‍👦', '💛', '🍩'], answer: 'The Simpsons', hints: ['Fox', 'Yellow', 'Springfield'] },
        { id: 't9', emojis: ['🦸', '⚡'], answer: 'The Flash', hints: ['CW', 'DC', 'Speedster'] },
        { id: 't10', emojis: ['👑', '🏰'], answer: 'The Crown', hints: ['Netflix', 'Queen', 'Royal'] },
        { id: 't11', emojis: ['🔍', '🧥'], answer: 'Sherlock', hints: ['BBC', 'Detective', 'Holmes'] },
        { id: 't12', emojis: ['🌉', '9️⃣', '9️⃣'], answer: 'Brooklyn Nine-Nine', hints: ['NBC', 'Police', 'Comedy'] },
        { id: 't13', emojis: ['🏥', '❤️'], answer: 'Greys Anatomy', hints: ['ABC', 'Medical', 'Drama'] },
        { id: 't14', emojis: ['😈', '🍳'], answer: 'Hells Kitchen', hints: ['Fox', 'Gordon', 'Cooking'] },
        { id: 't15', emojis: ['🏝️', '✈️', '❓'], answer: 'Lost', hints: ['ABC', 'Island', 'Mystery'] },
        { id: 't16', emojis: ['🧽', '🍍', '🌊'], answer: 'SpongeBob SquarePants', hints: ['Nickelodeon', 'Bikini Bottom', 'Patrick'] },
        { id: 't17', emojis: ['🦇', '🌃'], answer: 'Gotham', hints: ['Fox', 'Batman', 'Origin'] },
        { id: 't18', emojis: ['🚀', '🌌', '👨‍🚀'], answer: 'Star Trek', hints: ['Paramount', 'Space', 'Enterprise'] },
        { id: 't19', emojis: ['💃', '⭐'], answer: 'Dancing with the Stars', hints: ['ABC', 'Competition', 'Dance'] },
        { id: 't20', emojis: ['🎤', '😷'], answer: 'The Masked Singer', hints: ['Fox', 'Costumes', 'Singing'] },
        { id: 't21', emojis: ['🚗', '🔧'], answer: 'Top Gear', hints: ['BBC', 'Cars', 'Clarkson'] },
        { id: 't22', emojis: ['🏠', '👨‍👩‍👧‍👦', '😂'], answer: 'Full House', hints: ['ABC', 'Tanners', 'San Francisco'] },
        { id: 't23', emojis: ['👦', '🐕', '🔬'], answer: 'Jimmy Neutron', hints: ['Nickelodeon', 'Genius', 'Goddard'] },
        { id: 't24', emojis: ['🎤', '🏆'], answer: 'American Idol', hints: ['Fox', 'Singing', 'Competition'] },
        { id: 't25', emojis: ['🏠', '🔨'], answer: 'Home Improvement', hints: ['ABC', 'Tim Allen', 'Tools'] },
        { id: 't26', emojis: ['🧛', '😍'], answer: 'The Vampire Diaries', hints: ['CW', 'Stefan', 'Elena'] },
        { id: 't27', emojis: ['👩‍⚕️', '🏥'], answer: 'House', hints: ['Fox', 'Lupus', 'Diagnostic'] },
        { id: 't28', emojis: ['🍔', '👨‍🍳'], answer: 'Bobs Burgers', hints: ['Fox', 'Animation', 'Family'] },
        { id: 't29', emojis: ['⚡', '🦸', '👧'], answer: 'Supergirl', hints: ['CW', 'DC', 'Kara'] },
        { id: 't30', emojis: ['🎭', '📺'], answer: 'Saturday Night Live', hints: ['NBC', 'Sketch', 'Comedy'] },
        { id: 't31', emojis: ['🌴', '💰'], answer: 'Survivor', hints: ['CBS', 'Reality', 'Tribal Council'] },
        { id: 't32', emojis: ['🏀', '🎓'], answer: 'One Tree Hill', hints: ['CW', 'Basketball', 'Drama'] },
        { id: 't33', emojis: ['👶', '👴'], answer: 'This Is Us', hints: ['NBC', 'Family', 'Drama'] },
        { id: 't34', emojis: ['🍕', '🐢', '🥷'], answer: 'Teenage Mutant Ninja Turtles', hints: ['Nickelodeon', 'Heroes', 'Shredder'] },
        { id: 't35', emojis: ['🏈', '⏰'], answer: 'Friday Night Lights', hints: ['NBC', 'Texas', 'Football'] },
        { id: 't36', emojis: ['👨‍👩‍👧‍👦', '🦴'], answer: 'The Flintstones', hints: ['Hanna-Barbera', 'Stone Age', 'Bedrock'] },
        { id: 't37', emojis: ['🐕', '🔍'], answer: 'Scooby-Doo', hints: ['Cartoon', 'Mystery', 'Shaggy'] },
        { id: 't38', emojis: ['👩‍🎤', '🎤'], answer: 'Hannah Montana', hints: ['Disney', 'Miley', 'Double Life'] },
        { id: 't39', emojis: ['🧙‍♂️', '🏰'], answer: 'Merlin', hints: ['BBC', 'Arthur', 'Magic'] },
        { id: 't40', emojis: ['🎪', '🤡'], answer: 'American Horror Story', hints: ['FX', 'Horror', 'Anthology'] },
        { id: 't41', emojis: ['🏠', '👧', '👧', '👧'], answer: 'Powerpuff Girls', hints: ['Cartoon Network', 'Superheroes', 'Blossom'] },
        { id: 't42', emojis: ['🎵', '🚌'], answer: 'Glee', hints: ['Fox', 'Choir', 'High School'] },
        { id: 't43', emojis: ['👴', '🌊'], answer: 'SpongeBob SquarePants', hints: ['Nickelodeon', 'Squidward', 'Krabby Patty'] },
        { id: 't44', emojis: ['🦁', '👑', '🌍'], answer: 'The Lion Guard', hints: ['Disney', 'Kion', 'Pride Lands'] },
        { id: 't45', emojis: ['🎸', '👦'], answer: 'School of Rock', hints: ['Nickelodeon', 'Music', 'Kids'] },
        { id: 't46', emojis: ['🚒', '👨‍🚒'], answer: 'Chicago Fire', hints: ['NBC', 'Firefighters', 'Drama'] },
        { id: 't47', emojis: ['🔫', '👮'], answer: 'NCIS', hints: ['CBS', 'Military', 'Crime'] },
        { id: 't48', emojis: ['🎤', '🪑'], answer: 'The Voice', hints: ['NBC', 'Singing', 'Coaches'] },
        { id: 't49', emojis: ['🏠', '💰', '🔨'], answer: 'Fixer Upper', hints: ['HGTV', 'Renovation', 'Waco'] },
        { id: 't50', emojis: ['👩‍🍳', '🔪', '🏆'], answer: 'MasterChef', hints: ['Fox', 'Cooking', 'Ramsay'] },
        { id: 't51', emojis: ['🦈', '💰'], answer: 'Shark Tank', hints: ['ABC', 'Business', 'Investors'] },
        { id: 't52', emojis: ['👗', '🏃'], answer: 'Project Runway', hints: ['Bravo', 'Fashion', 'Heidi Klum'] },
        { id: 't53', emojis: ['🌍', '🏃', '💰'], answer: 'The Amazing Race', hints: ['CBS', 'Travel', 'Competition'] },
        { id: 't54', emojis: ['💍', '🌹'], answer: 'The Bachelor', hints: ['ABC', 'Dating', 'Rose Ceremony'] },
        { id: 't55', emojis: ['🏠', '👫', '💔'], answer: 'Big Brother', hints: ['CBS', 'Reality', 'Eviction'] },
        { id: 't56', emojis: ['🧲', '👨‍🔬'], answer: 'The Big Bang Theory', hints: ['CBS', 'Nerds', 'Physics'] },
        { id: 't57', emojis: ['👨‍👦', '🎣'], answer: 'Andy Griffith Show', hints: ['CBS', 'Mayberry', 'Classic'] },
        { id: 't58', emojis: ['🎭', '🎬'], answer: 'Curb Your Enthusiasm', hints: ['HBO', 'Larry David', 'Comedy'] },
        { id: 't59', emojis: ['🏀', '🎤'], answer: 'The Fresh Prince of Bel-Air', hints: ['NBC', 'Will Smith', 'Philly'] },
        { id: 't60', emojis: ['🤖', '❤️'], answer: 'Westworld', hints: ['HBO', 'AI', 'Theme Park'] },
        { id: 't61', emojis: ['👨‍⚕️', '🔬', '👧'], answer: 'Bones', hints: ['Fox', 'Forensic', 'Brennan'] },
        { id: 't62', emojis: ['🐎', '🤠'], answer: 'Yellowstone', hints: ['Paramount', 'Ranch', 'Costner'] },
        { id: 't63', emojis: ['🦸', '👧', '💫'], answer: 'WandaVision', hints: ['Disney+', 'Marvel', 'Sitcom'] },
        { id: 't64', emojis: ['👨‍👩‍👧', '🏠', '80s'], answer: 'The Goldbergs', hints: ['ABC', 'Family', 'Nostalgia'] },
        { id: 't65', emojis: ['🧟', '👧', '🧠'], answer: 'iZombie', hints: ['CW', 'Zombie', 'Brains'] },
    ],
    medium: [
        { id: 't66', emojis: ['🎰', '🏜️'], answer: 'Fallout', hints: ['Amazon', 'Vault', 'Apocalypse'] },
        { id: 't67', emojis: ['⚔️', '🛡️', '🗺️'], answer: 'Vikings', hints: ['History', 'Ragnar', 'Norse'] },
        { id: 't68', emojis: ['👮', '🔬'], answer: 'CSI', hints: ['CBS', 'Crime', 'Forensics'] },
        { id: 't69', emojis: ['🎭', '🔪', '💀'], answer: 'Dexter', hints: ['Showtime', 'Serial', 'Killer'] },
        { id: 't70', emojis: ['💼', '⚖️'], answer: 'Suits', hints: ['USA', 'Lawyers', 'Harvey'] },
        { id: 't71', emojis: ['👨', '👨', '👦'], answer: 'Two and a Half Men', hints: ['CBS', 'Sitcom', 'Charlie'] },
        { id: 't72', emojis: ['🧙‍♂️', '📚'], answer: 'Harry Potter', hints: ['HBO', 'Wizards', 'Hogwarts'] },
        { id: 't73', emojis: ['🎯', '🏹'], answer: 'Arrow', hints: ['CW', 'DC', 'Oliver'] },
        { id: 't74', emojis: ['💛', '🪨'], answer: 'Yellowstone', hints: ['Paramount', 'Ranch', 'Montana'] },
        { id: 't75', emojis: ['🎪', '🔮'], answer: 'Carnival Row', hints: ['Amazon', 'Fantasy', 'Fae'] },
        { id: 't76', emojis: ['🧪', '👨‍🔬', '💰'], answer: 'Breaking Bad', hints: ['Walter White', 'Meth', 'Heisenberg'] },
        { id: 't77', emojis: ['🔍', '🧩'], answer: 'Mindhunter', hints: ['Netflix', 'FBI', 'Serial Killers'] },
        { id: 't78', emojis: ['🌲', '☕', '🦉'], answer: 'Twin Peaks', hints: ['Lynch', 'Mystery', 'Laura'] },
        { id: 't79', emojis: ['💉', '🩸', '🧛'], answer: 'True Blood', hints: ['HBO', 'Vampires', 'Louisiana'] },
        { id: 't80', emojis: ['👨‍✈️', '🏝️'], answer: 'Magnum P.I.', hints: ['CBS', 'Hawaii', 'Detective'] },
        { id: 't81', emojis: ['🚔', '👮', '🌃'], answer: 'Law and Order', hints: ['NBC', 'Crime', 'Courts'] },
        { id: 't82', emojis: ['🔪', '🍳', '🏆'], answer: 'Chopped', hints: ['Food Network', 'Cooking', 'Basket'] },
        { id: 't83', emojis: ['🐉', '⚔️', '🏯'], answer: 'House of the Dragon', hints: ['HBO', 'Targaryen', 'Prequel'] },
        { id: 't84', emojis: ['⚖️', '👨‍⚖️'], answer: 'Better Call Saul', hints: ['AMC', 'Jimmy', 'Lawyer'] },
        { id: 't85', emojis: ['🕵️', '🔎', '👩'], answer: 'Veronica Mars', hints: ['Neptune', 'Detective', 'Teen'] },
        { id: 't86', emojis: ['🧠', '❤️', '🔬'], answer: 'The Good Doctor', hints: ['ABC', 'Autism', 'Surgeon'] },
        { id: 't87', emojis: ['🏰', '👸', '📜'], answer: 'Bridgerton', hints: ['Netflix', 'Regency', 'Romance'] },
        { id: 't88', emojis: ['🎭', '😱'], answer: 'You', hints: ['Netflix', 'Stalker', 'Joe'] },
        { id: 't89', emojis: ['🌌', '👽'], answer: 'The Expanse', hints: ['Amazon', 'Space', 'Belt'] },
        { id: 't90', emojis: ['🎪', '🔥'], answer: 'Lucifer', hints: ['Netflix', 'Devil', 'LA'] },
        { id: 't91', emojis: ['👨‍👩‍👧', '🏠', '🎭'], answer: 'Succession', hints: ['HBO', 'Wealthy', 'Media'] },
        { id: 't92', emojis: ['💵', '💵', '💵'], answer: 'Billions', hints: ['Showtime', 'Wall Street', 'Hedge Fund'] },
        { id: 't93', emojis: ['🔫', '🤠', '🏜️'], answer: 'Westworld', hints: ['HBO', 'Robots', 'Cowboys'] },
        { id: 't94', emojis: ['👁️', '🔺'], answer: 'The OA', hints: ['Netflix', 'Mystery', 'Dimension'] },
        { id: 't95', emojis: ['🌲', '💀', '🔍'], answer: 'True Detective', hints: ['HBO', 'Crime', 'Anthology'] },
        { id: 't96', emojis: ['⚡', '☔'], answer: 'The Umbrella Academy', hints: ['Netflix', 'Superheroes', 'Dysfunctional'] },
        { id: 't97', emojis: ['🎭', '📖'], answer: 'The Handmaids Tale', hints: ['Hulu', 'Dystopia', 'Gilead'] },
        { id: 't98', emojis: ['🕵️', '🔐'], answer: 'Prison Break', hints: ['Fox', 'Escape', 'Tattoo'] },
        { id: 't99', emojis: ['🧬', '🔬', '🧪'], answer: 'Orphan Black', hints: ['BBC', 'Clones', 'Sarah'] },
        { id: 't100', emojis: ['👑', '♟️'], answer: 'The Queens Gambit', hints: ['Netflix', 'Chess', 'Beth'] },
        { id: 't101', emojis: ['🎭', '🎤', '📺'], answer: 'Late Night with Jimmy Fallon', hints: ['NBC', 'Talk Show', 'Tonight'] },
        { id: 't102', emojis: ['🚀', '👨‍🚀', '🔴'], answer: 'For All Mankind', hints: ['Apple TV', 'Space Race', 'Alternate History'] },
        { id: 't103', emojis: ['🤖', '🔫', '🌆'], answer: 'Person of Interest', hints: ['CBS', 'AI', 'Surveillance'] },
        { id: 't104', emojis: ['🔪', '👩', '📖'], answer: 'Killing Eve', hints: ['BBC', 'Assassin', 'Obsession'] },
        { id: 't105', emojis: ['🏠', '🔥', '👨‍👩‍👧'], answer: 'Little Fires Everywhere', hints: ['Hulu', 'Drama', 'Secrets'] },
        { id: 't106', emojis: ['🌊', '⛵', '💀'], answer: 'Black Sails', hints: ['Starz', 'Pirates', 'Treasure Island'] },
        { id: 't107', emojis: ['🔫', '🏴‍☠️', '🌴'], answer: 'Outer Banks', hints: ['Netflix', 'Treasure', 'Teen'] },
        { id: 't108', emojis: ['👨‍⚕️', '💀', '🔬'], answer: 'The Knick', hints: ['Cinemax', 'Surgery', '1900s'] },
        { id: 't109', emojis: ['🎭', '👧', '🧠'], answer: 'Fleabag', hints: ['Amazon', 'Comedy', 'British'] },
        { id: 't110', emojis: ['🎹', '💕'], answer: 'Normal People', hints: ['Hulu', 'Ireland', 'Romance'] },
        { id: 't111', emojis: ['👨‍👩‍👧‍👦', '🇮🇹'], answer: 'The Sopranos', hints: ['HBO', 'Mafia', 'Tony'] },
        { id: 't112', emojis: ['🔫', '🏠', '👨‍👩‍👧‍👦'], answer: 'Ozark', hints: ['Netflix', 'Money Laundering', 'Missouri'] },
        { id: 't113', emojis: ['🎭', '🌃', '💰'], answer: 'Mad Men', hints: ['AMC', 'Advertising', '1960s'] },
        { id: 't114', emojis: ['👩‍🎤', '🎤', '⭐'], answer: 'Empire', hints: ['Fox', 'Music', 'Lyon'] },
        { id: 't115', emojis: ['🔍', '😈'], answer: 'Mindhunter', hints: ['Netflix', 'FBI', 'Profiler'] },
        { id: 't116', emojis: ['🐺', '🌙'], answer: 'Teen Wolf', hints: ['MTV', 'Werewolf', 'Scott'] },
        { id: 't117', emojis: ['🏰', '🐉', '⚔️'], answer: 'Game of Thrones', hints: ['Iron Throne', 'Stark', 'Lannister'] },
        { id: 't118', emojis: ['🎪', '🎭', '😈'], answer: 'American Horror Story Freak Show', hints: ['FX', 'Circus', 'Horror'] },
        { id: 't119', emojis: ['👨‍🍳', '🔥', '🍳'], answer: 'The Bear', hints: ['FX', 'Chicago', 'Restaurant'] },
        { id: 't120', emojis: ['💊', '🏥', '😷'], answer: 'New Amsterdam', hints: ['NBC', 'Hospital', 'Doctor'] },
        { id: 't121', emojis: ['🧙‍♀️', '📖', '🌲'], answer: 'Charmed', hints: ['WB', 'Sisters', 'Magic'] },
        { id: 't122', emojis: ['🐉', '👧', '🔥'], answer: 'Game of Thrones', hints: ['Daenerys', 'Mother of Dragons', 'Khaleesi'] },
        { id: 't123', emojis: ['🚨', '🏥'], answer: 'ER', hints: ['NBC', 'Emergency Room', 'Clooney'] },
        { id: 't124', emojis: ['🗡️', '🛡️', '👨‍👩‍👧‍👦'], answer: 'The Last Kingdom', hints: ['Netflix', 'Vikings', 'Uhtred'] },
        { id: 't125', emojis: ['🎰', '🌃', '👑'], answer: 'Peaky Blinders', hints: ['BBC', 'Birmingham', 'Tommy'] },
        { id: 't126', emojis: ['🤖', '🌌'], answer: 'Battlestar Galactica', hints: ['Syfy', 'Cylons', 'Space'] },
        { id: 't127', emojis: ['🧟', '🧠', '👨‍👩‍👧‍👦'], answer: 'The Walking Dead', hints: ['Rick', 'Daryl', 'Negan'] },
        { id: 't128', emojis: ['🎭', '🎪', '🔴'], answer: 'The Marvelous Mrs. Maisel', hints: ['Amazon', 'Comedy', '1950s'] },
        { id: 't129', emojis: ['💎', '🏃‍♂️', '💰'], answer: 'Money Heist', hints: ['Netflix', 'Spanish', 'Heist'] },
        { id: 't130', emojis: ['🔴', '🟢', '🔴'], answer: 'Squid Game', hints: ['Netflix', 'Korean', 'Games'] },
    ],
    hard: [
        { id: 't131', emojis: ['⌛', '🕳️', '🔦'], answer: 'Dark', hints: ['Netflix', 'German', 'Time Travel'] },
        { id: 't132', emojis: ['🎩', '🔫', '🥃'], answer: 'Peaky Blinders', hints: ['BBC', 'Gangster', 'Birmingham'] },
        { id: 't133', emojis: ['🖥️', '🔓'], answer: 'Mr Robot', hints: ['USA', 'Hacker', 'Elliot'] },
        { id: 't134', emojis: ['📕', '👧'], answer: 'The Handmaids Tale', hints: ['Hulu', 'Dystopia', 'Gilead'] },
        { id: 't135', emojis: ['🧬', '🔄'], answer: 'Orphan Black', hints: ['BBC', 'Clones', 'Sarah'] },
        { id: 't136', emojis: ['👯', '🏔️'], answer: 'Twin Peaks', hints: ['ABC', 'Lynch', 'Mystery'] },
        { id: 't137', emojis: ['🎭', '🗡️'], answer: 'Westworld', hints: ['HBO', 'Robots', 'Park'] },
        { id: 't138', emojis: ['📞', '💵'], answer: 'Better Call Saul', hints: ['AMC', 'Lawyer', 'Prequel'] },
        { id: 't139', emojis: ['🛸', '👾'], answer: 'The X-Files', hints: ['Fox', 'FBI', 'Aliens'] },
        { id: 't140', emojis: ['🏠', '🔪', '😨'], answer: 'American Horror Story', hints: ['FX', 'Horror', 'Murder House'] },
        { id: 't141', emojis: ['🔭', '🌌', '📡'], answer: 'Cosmos', hints: ['NatGeo', 'Space', 'Sagan'] },
        { id: 't142', emojis: ['🧠', '🔮'], answer: 'Sense8', hints: ['Netflix', 'Psychic', 'Cluster'] },
        { id: 't143', emojis: ['🎹', '🎤', '🌃'], answer: 'The Eddy', hints: ['Netflix', 'Jazz', 'Paris'] },
        { id: 't144', emojis: ['⚗️', '📚', '🏛️'], answer: 'Breaking Bad', hints: ['Chemistry', 'Teacher', 'Cancer'] },
        { id: 't145', emojis: ['🕵️', '🎭', '🇬🇧'], answer: 'Sherlock', hints: ['Cumberbatch', 'Watson', 'Moriarty'] },
        { id: 't146', emojis: ['🏴‍☠️', '⚓', '🦜'], answer: 'Our Flag Means Death', hints: ['HBO', 'Pirates', 'Comedy'] },
        { id: 't147', emojis: ['🎺', '🎷', '🌙'], answer: 'Treme', hints: ['HBO', 'New Orleans', 'Music'] },
        { id: 't148', emojis: ['🏛️', '⚖️', '🇺🇸'], answer: 'House of Cards', hints: ['Netflix', 'Politics', 'Underwood'] },
        { id: 't149', emojis: ['💉', '👩‍⚕️', '🔬'], answer: 'Nurse Jackie', hints: ['Showtime', 'Addiction', 'Hospital'] },
        { id: 't150', emojis: ['🔪', '🍖', '🎭'], answer: 'Hannibal', hints: ['NBC', 'Cannibal', 'Lecter'] },
        { id: 't151', emojis: ['🎭', '📚', '🖋️'], answer: 'Downton Abbey', hints: ['PBS', 'British', 'Estate'] },
        { id: 't152', emojis: ['⚔️', '🏹', '🐺'], answer: 'Game of Thrones', hints: ['Stark', 'Dire Wolf', 'Winter'] },
        { id: 't153', emojis: ['🌲', '🔍', '📹'], answer: 'Twin Peaks The Return', hints: ['Showtime', 'Cooper', 'Black Lodge'] },
        { id: 't154', emojis: ['🎭', '🌃', '🔫'], answer: 'The Wire', hints: ['HBO', 'Baltimore', 'Drug Trade'] },
        { id: 't155', emojis: ['🌴', '☀️', '💊'], answer: 'White Lotus', hints: ['HBO', 'Resort', 'Satire'] },
        { id: 't156', emojis: ['📺', '😂', '🎭'], answer: '30 Rock', hints: ['NBC', 'Tina Fey', 'Sketch Show'] },
        { id: 't157', emojis: ['🎪', '👻', '🏚️'], answer: 'The Haunting of Hill House', hints: ['Netflix', 'Horror', 'Ghosts'] },
        { id: 't158', emojis: ['🏰', '👸', '📜'], answer: 'The Tudors', hints: ['Showtime', 'Henry VIII', 'England'] },
        { id: 't159', emojis: ['🎭', '📱', '😱'], answer: 'Black Mirror', hints: ['Netflix', 'Technology', 'Anthology'] },
        { id: 't160', emojis: ['🔫', '🚗', '💵'], answer: 'Breaking Bad', hints: ['RV', 'Desert', 'Blue'] },
        { id: 't161', emojis: ['⚡', '🌧️', '🌪️'], answer: 'Under the Dome', hints: ['CBS', 'Stephen King', 'Barrier'] },
        { id: 't162', emojis: ['🔮', '👁️', '🌌'], answer: 'Legion', hints: ['FX', 'X-Men', 'Mutant'] },
        { id: 't163', emojis: ['🎹', '🎵', '👨‍🎤'], answer: 'Mozart in the Jungle', hints: ['Amazon', 'Orchestra', 'Classical'] },
        { id: 't164', emojis: ['👻', '🏠', '📸'], answer: 'The Haunting of Bly Manor', hints: ['Netflix', 'Horror', 'Ghosts'] },
        { id: 't165', emojis: ['🔬', '🧪', '👽'], answer: 'Fringe', hints: ['Fox', 'Parallel', 'Universe'] },
        { id: 't166', emojis: ['⏰', '🔄', '😵'], answer: 'Russian Doll', hints: ['Netflix', 'Time Loop', 'Nadia'] },
        { id: 't167', emojis: ['🗡️', '🏛️', '🦅'], answer: 'Rome', hints: ['HBO', 'Ancient', 'Caesar'] },
        { id: 't168', emojis: ['🌲', '🏠', '👨‍👩‍👧‍👦'], answer: 'Yellowjackets', hints: ['Showtime', 'Crash', 'Cannibalism'] },
        { id: 't169', emojis: ['🎭', '💃', '🌃'], answer: 'Pose', hints: ['FX', 'Ballroom', 'LGBTQ'] },
        { id: 't170', emojis: ['🔴', '⬛', '🃏'], answer: 'Squid Game', hints: ['Korean', 'Debt', 'Childhood Games'] },
        { id: 't171', emojis: ['🎰', '🌴', '🔫'], answer: 'Vice', hints: ['HBO', 'News', 'Documentary'] },
        { id: 't172', emojis: ['👽', '🔬', '🏜️'], answer: 'Roswell', hints: ['WB', 'Aliens', 'New Mexico'] },
        { id: 't173', emojis: ['🚀', '🌌', '⚔️'], answer: 'The Mandalorian', hints: ['Disney+', 'Star Wars', 'Baby Yoda'] },
        { id: 't174', emojis: ['🌲', '⛺', '👦'], answer: 'Gravity Falls', hints: ['Disney', 'Mystery', 'Twins'] },
        { id: 't175', emojis: ['🧪', '🦠', '😷'], answer: 'The Last of Us', hints: ['HBO', 'Fungus', 'Joel'] },
        { id: 't176', emojis: ['👸', '🏰', '📖'], answer: 'Anne with an E', hints: ['Netflix', 'Orphan', 'Canada'] },
        { id: 't177', emojis: ['🌙', '🧛', '🦇'], answer: 'What We Do in the Shadows', hints: ['FX', 'Vampires', 'Comedy'] },
        { id: 't178', emojis: ['🔫', '🕵️', '🇷🇺'], answer: 'The Americans', hints: ['FX', 'Spies', 'Cold War'] },
        { id: 't179', emojis: ['🌊', '⛵', '🏝️'], answer: 'Lost', hints: ['Dharma', 'Others', 'Smoke Monster'] },
        { id: 't180', emojis: ['👨‍⚖️', '📺', '😠'], answer: 'Judge Judy', hints: ['Courtroom', 'Reality', 'Cases'] },
        { id: 't181', emojis: ['🎹', '🌧️', '💔'], answer: 'BoJack Horseman', hints: ['Netflix', 'Animation', 'Hollywood'] },
        { id: 't182', emojis: ['🌌', '🚀', '👩‍🚀'], answer: 'Star Trek Discovery', hints: ['Paramount', 'Burnham', 'Federation'] },
        { id: 't183', emojis: ['🔴', '⚫', '🔵'], answer: 'Ted Lasso', hints: ['Apple TV', 'Soccer', 'Coach'] },
        { id: 't184', emojis: ['🧙‍♂️', '📚', '⚔️'], answer: 'The Witcher', hints: ['Netflix', 'Geralt', 'Monster Hunter'] },
        { id: 't185', emojis: ['🌹', '🏰', '🧙'], answer: 'Once Upon a Time', hints: ['ABC', 'Fairy Tale', 'Storybrooke'] },
        { id: 't186', emojis: ['🔍', '🧩', '🎭'], answer: 'Only Murders in the Building', hints: ['Hulu', 'Podcast', 'Steve Martin'] },
        { id: 't187', emojis: ['🐻', '❄️', '🌲'], answer: 'Northern Exposure', hints: ['CBS', 'Alaska', 'Quirky'] },
        { id: 't188', emojis: ['🍳', '🔥', '😤'], answer: 'The Bear', hints: ['FX', 'Carmy', 'Beef'] },
        { id: 't189', emojis: ['🏴‍☠️', '👨‍👩‍👧‍👦', '🔫'], answer: 'The Sopranos', hints: ['HBO', 'Mob', 'New Jersey'] },
        { id: 't190', emojis: ['🌍', '🦠', '😷'], answer: 'The Last of Us', hints: ['HBO', 'Cordyceps', 'Ellie'] },
        { id: 't191', emojis: ['🎪', '🃏', '😈'], answer: 'Joker', hints: ['HBO', 'Origin', 'Arthur'] },
        { id: 't192', emojis: ['📱', '💔', '🔍'], answer: 'Black Mirror', hints: ['Anthology', 'Tech', 'Dystopia'] },
        { id: 't193', emojis: ['🌲', '🔦', '👻'], answer: 'Stranger Things', hints: ['Upside Down', 'Demogorgon', 'Vecna'] },
        { id: 't194', emojis: ['🗡️', '❄️', '🐺'], answer: 'Game of Thrones', hints: ['Jon Snow', 'Night King', 'Wall'] },
        { id: 't195', emojis: ['🎭', '🖋️', '📺'], answer: 'Atlanta', hints: ['FX', 'Donald Glover', 'Music'] },
        { id: 't196', emojis: ['🌙', '🧙‍♀️', '🔮'], answer: 'The Chilling Adventures of Sabrina', hints: ['Netflix', 'Witch', 'Teen'] },
        { id: 't197', emojis: ['🧬', '🔬', '💀'], answer: 'Severance', hints: ['Apple TV', 'Work', 'Memory'] },
        { id: 't198', emojis: ['👨‍👩‍👧', '🏠', '🔪'], answer: 'The Sinner', hints: ['USA', 'Crime', 'Why'] },
        { id: 't199', emojis: ['🌺', '🎸', '💀'], answer: 'Coco', hints: ['Disney', 'Mexico', 'Dia de Muertos'] },
        { id: 't200', emojis: ['🎪', '🐘', '🌟'], answer: 'Dumbo', hints: ['Disney', 'Circus', 'Flying'] },
    ],
};

window.TVSHOW_PUZZLES = TVSHOW_PUZZLES;
